### ISSUE TITLE
Add optional traceback prettyprinting

### ISSUE THREAD

**Issue by thedrow** [nose-devs/nose2#103]
Pygments supports prettyprinting tracebacks both for python 2.x & 3.x.
This feature should detect if Pygments is installed, if it is it should prettyprint the traceback by default. There will be a reporter configuration option to disable prettyprinting completely.
To ensure terminal colors are supported on windows Colorama should be used.
Both Pygments & Colorama dependencies should be specified in the setup's extra_requires.

**Comment by sirosen** [comment]
Given the current support/maintenance status of `nose2`, I don't think it's likely that I will work on this feature.
It would still be accepted if someone wanted to contribute a PR, but until then, I'm closing as unplanned.
