### ISSUE TITLE
Add optional colors for test results

### ISSUE THREAD

**Issue by thedrow** [nose-devs/nose2#104]
This feature should detect if Colorama is installed, if it is it should colorize the test results by default. There will be a reporter configuration option to disable colorizing completely.
There will be configuration options that will allow to assign different colors for each test result.
By default the following colors will be used:
- Passed - Green.
- Failed - Red.
- Error - Bold Red.
- Skipped - Yellow.
- Expected Failure - Dim Red.
- Unexpected Success - Dim Green.
- Other Outcome - Cyan.
  To ensure terminal colors are supported on windows Colorama should be used.
  The Colorama dependency should be specified in the setup's extra_requires.

**Comment by sirosen** [comment]
Given the current support/maintenance status of `nose2`, I don't think it's likely that I will work on this feature.
It would still be accepted if someone wanted to contribute a PR, but until then, I'm closing as unplanned.
