### ISSUE TITLE
the multiprocess plugin fails to give a useful error for unimportable test modules

### ISSUE THREAD

**Issue by sanga** [nose-devs/nose2#109]
So if a test module is not importable you wind up with the following output:

```
test_not_found (nose2.loader.LoadTestsFailure) ... ERROR
test_not_found (nose2.loader.LoadTestsFailure) ... ERROR

======================================================================
ERROR: test_not_found (nose2.loader.LoadTestsFailure)
----------------------------------------------------------------------
AttributeError: 'module' object has no attribute 'ModuleImportFailure'
```

The reason for this so far as I can tell is that the mp plugin first imports the tests in the main process and then distributes those tests across the child processes by name, where they are again imported. The problem arises because for a module which can't be imported, nose2 creates a testsuite with a method that will just raise the import exception when run. Like so:

```
unittest2.suite.TestSuite tests=[<nose2.loader.ModuleImportFailure testMethod=v2.test_token>]
```

 mp.MultiProcess._flatten ends up making those into the following list of 'test names'

```
flat: ['nose2.loader.ModuleImportFailure.v2.test_object_relations',
'nose2.loader.ModuleImportFailure.v2.test_devices...
```

and when the child process tries to import the name 
nose2.loader.ModuleImportFailure.v2.test_object_relations
it fails as that test doesn't exist.

And so the root cause of the import error is lost.

so how might one fix this?
in a way it doesn't make sense to farm those tests that can't be imported
out to the child nose processes, as we already know that they fail, so we
could filter them out already before the _flatten process
my attempts to do that though haven't so far succeeded

It might be easier to just change the test name in that case (util.test_id I think does that) so that nose2.loader.ModuleImportFailure would be removed so that the child process could actually find the test to import, and so that would catch the import error. Though test names must match in both the main and the child processes.

**Comment by moosingin3space** [comment]
Has any progress been made on this?

**Comment by nicolasdomeniconi** [comment]
Looks like this is still an issue.

**Comment by cdman** [comment]
This still happens with nose2 0.6.4

**Comment by jaredj** [comment]
Still in 0.6.5 as well

**Comment by ibnIrshad** [comment]
At least a quick google search of the error leads to this issue page, which helps in diagnosing the problem.

**Comment by TyberiusPrime** [comment]
I have a pretty ugly hack to get the right output (see below, it does pass the test suite...), 
but I think the methodology is sound.

```patch
--- a/nose2/plugins/mp.py	Tue Oct 10 10:20:56 2017 +0200
+++ b/nose2/plugins/mp.py	Tue Oct 10 11:05:28 2017 +0200
@@ -69,6 +69,12 @@
 
     def _runmp(self, test, result):
         flat = list(self._flatten(test))
+        # do not send import failures to the subprocesses, which will mangle tthem
+        # but 'run' them in the main process.
+        flat = [x for x in flat if not x.startswith('nose2.loader.ModuleImportFailure')]
+        for t in test:
+            l  = list(self._flatten(t))
+            if l and l[0].startswith('nose2.loader.ModuleImportFailure'):
+                result_ =  self.session.testResult
+                t.run(result_)
         procs = self._startProcs(len(flat))
```

**Comment by katrinabrock** [comment]
This would be really nice to have fixed. If someone is willing to write a test case for this, and I can clean up @TyberiusPrime 's code for readability and merge.

**Comment by ptthiem** [comment]
I have this issue on my hit list, shouldn't take too long

**Comment by artragis** [comment]
@katrinabrock can this one and  #250 be closed?
