### ISSUE TITLE
nose2 seems to requires unittest2

### ISSUE THREAD

**Issue by warsaw** [nose-devs/nose2#118]
setup.py has this line:

```
if sys.version_info < (2, 7):
    REQS.extend(['unittest2>=0.5.1,<0.6', 'argparse>=1.2.1,<1.3'])
```

but also this line:

```
params['test_suite'] = 'nose2.compat.unittest.collector'
```

However, Python 2.7's unittest does not have a 'collector' attribute.

**Comment by sirosen** [comment]
This was definitely resolved at some point, but never closed.

_I am doing some old issue cleanup. Sorry about the inevitable notifications!_
