### ISSUE TITLE
Consider using mozilla's konfig instead of using our own objects

### ISSUE THREAD

**Issue by thedrow** [nose-devs/nose2#152]
https://github.com/mozilla-services/konfig is a proven configuration library that does exactly what we need and what nose2 already implements.
It might reduce our maintenance overhead.
We should consider replacing our own configuration system with konfig.

**Comment by sirosen** [comment]
I don't think `konfig` has really taken off; I'd be extremely hesitant to use it.

If there's going to be a major change to the way config is handled at this stage, we'd probably use the updated `configparser` (pulling in the backport for py2) OR use a new format entirely, e.g. vendor pytoml and use TOML config.

But given the reduced work this project is seeing, it's unlikely we'll make any changes on this front, at least for the forseeable future.
