### ISSUE TITLE
nose2 cant import tests from package

### ISSUE THREAD

**Issue by tgomd** [nose-devs/nose2#161]
I have set up a virtual env and have a test structure that looks something like this:
<path>/test_package/__init__.py
                                 test_foo.py:test_bar

test_bar is a really simple test, it just passes.
When I stand in "<path>/test_package" and run "nose2" I get an error:
"ImportError: No module named test_package.test_foo"
But it works with nosetests.
And if I stand in "<path>" and run "nose2 test_package" it works, and it also works if I remove the __init__.py

I know that the collection of tests work a little different than in nosetests, but I think that it would be good to make this work since it would make it easier to create a test package and run it.

**Comment by thedrow** [comment]
@tgomd Can you please verify that #161 fixes your issue?
