### ISSUE TITLE
Output clover-formatted JUnit XML

### ISSUE THREAD

**Issue by dan-blanchard** [nose-devs/nose2#198]
Is there any way to generate Clover-compatible JUnit XML with nose2 like you used to be able to do with [NoseXUnit](http://nosexunit.sourceforge.net)? If not, could you please add that to your lengthy to-do list? :smile: 

Those of us who are using Atlassian Bamboo for testing are missing out on coverage reports because there's no way to do this with nose2 at the moment.

**Comment by katrinabrock** [comment]
Not a priority for current maintainers. Would accept PR.
