### ISSUE TITLE
logCapture plugin prints logs for non-failed tests

### ISSUE THREAD

**Issue by warvariuc** [nose-devs/nose2#251]
The [docs](http://nose2.readthedocs.org/en/latest/_modules/nose2/plugins/logcapture.html) say:

> Capture log messages during test execution, appending them to the error reports of failed tests.

In my case the captured logs are printed even if a test didn't fail:

```
$ ./runtests.sh -v tests.test_application.Test.test_not_found
test_not_found (tests.test_application.Test) ... ERROR   Template not found: not_found/cfa.html
ok

----------------------------------------------------------------------
Ran 1 test in 0.668s

```

Configuration file:

```
[log-capture]
log-level = WARNING
```

Looking at the plugin code I didn't find any place where it's checked that the test failed.

**Comment by Bernhard10** [comment]
You need to activate the log-capture plugin with `always-on = True` or --log-capture

**Comment by warvariuc** [comment]
This works. Thank you!
