### ISSUE TITLE
Module level coverage missing

### ISSUE THREAD

**Issue by frenchtoast747** [nose-devs/nose2#253]
Say I have the coverage plugin installed, configured, and enabled and I have a simple test:

```.py
from unittest import TestCase

from my_module import returns_42

class MyTest(TestCase):
    def test_it(self):
        self.assertEqual(returns_42(), 42)
```

The test passes and all is good until I have a look at coverage report. The module level coverage is absent, but the function level coverage is present:

![coverage](https://cloud.githubusercontent.com/assets/1094000/10264286/a829f566-69cc-11e5-80a7-5e8ceadeea37.png)

According to [this StackOverflow question](http://stackoverflow.com/questions/9155854/getting-pythons-coverage-py-to-gather-coverage-for-the-module-that-imports-it), this behavior implies that coverage isn't being collected until *after* the test starts.

A work around would be to do something like this:

```.py
from unittest import TestCase

class MyTest(TestCase):
    def test_it(self):
        from my_module import returns_42
        self.assertEqual(returns_42(), 42)
```

which gives me the coverage I expect:

![coverage_i_expect](https://cloud.githubusercontent.com/assets/1094000/10264315/5916960e-69cd-11e5-97de-57a17111fea6.png)

however, that's not what I would consider an ideal solution. Is there an option or a setting that I am missing to fix this? Is there something else that I am missing?

**Comment by frenchtoast747** [comment]
For now I've written a lazy importing class to provide a module level variable representing the function/class under test. The implementation can be found [here](https://gist.github.com/frenchtoast747/6952847b8e0634ce9054) for anyone else who might be facing this issue.

Example usage:
```
from unittest import TestCase
from importing import lazy_import

returns_42 = lazy_import('my_module.returns_42')


class TestThing(TestCase):
    def test_it(self):
        self.assertEqual(returns_42(), 42)
```

The function or class is not imported until it is first used (in the above example, this would be during the `test_it` test). It works with functions and classes, but not variables. In the event that a variable is needed, the module itself will need to be imported and then just access via attributes.

**Note**: one caveat with the current implementation of `lazy_import` is that *you can't set any attributes* on the lazily import objects.

**Comment by ztane** [comment]
I was struck by this as well. The included coverage plugin is *supposed* to gather the import-time coverage data as well, but does not seem to do so.

**Comment by ztane** [comment]
(Using Coverage 4.0.0, and 3.7.1)

**Comment by ztane** [comment]
@frenchtoast747 actually it seems to be fixed at https://github.com/nose-devs/nose2/commit/268371d815fb319bda4489da9756843204354eab

**Comment by frenchtoast747** [comment]
Oh wow. Nice find @ztane. Thanks for letting me know.

**Comment by thedrow** [comment]
I'll try to do it on the weekend.

**Comment by ztane** [comment]
@thedrow @kumar303 @jpellerin nose2 is still at 0.5.0 at PyPI, could I be of any help (what is needed beyond just git tagging, bumping version, and uploading to pypi)?

**Comment by thedrow** [comment]
@ztane I've moved on to other projects unfortunately.
You might want to send a mail to the mailing list or contact @jpellerin directly if you want to maintain the project.

**Comment by ztane** [comment]
FWIW I switched to py.test and it worked right out of box for me as a nose2 replacement.

**Comment by saukymo** [comment]
I used the latest version in master and has the change at 268371d. But still not cover the def lines. Is there anything else I need to know? Thx.

**Comment by johnthagen** [comment]
I just ran into this same problem as well, would be really great to push a new tag to PyPI.

**Comment by little-dude** [comment]
@johnthagen I'll make a release soon. I just need the right to push on pypi. See https://github.com/nose-devs/nose2/issues/263

**Comment by little-dude** [comment]
nose2 0.6.0 has been pushed on pypi. Feel free to re-open if it does not fix the issue.
