### ISSUE TITLE
Add --output-format flag  

### ISSUE THREAD

**Issue by ojengwa** [nose-devs/nose2#254]
I have being looking out for this feature. Example of where this might come in handy would be in app that requires piping the output from the test runner to some other function. I have had to hack the internals to output JSON instead while building a TDD driven tutorial app for example. It helps that most other TDD frameworks in other languages already supports similar flags. 

I could send in a PR if for consideration if that helps...

**Comment by ztane** [comment]
If you look at https://github.com/nose-devs/nose2/issues/253 you'll realize what nose2 requires is a new *maintainer*, not just pull requests.

**Comment by little-dude** [comment]
Hi @ojengwa I'm now maintaining nose2. Sorry for coming back late on this, I'm just starting to catch up on open issues :)

I'm not really sure to understand what you mean here. To output json I use a custom plugin but it's quite specific to my own use case. I'd be interested in a PR, even a non-working one, to understand exactly what you want.

**Comment by katrinabrock** [comment]
Would accept a PR to output results in structured data format.
This is not a priority for me so or @little-dude so I am closing this issue.

**Comment by katrinabrock** [comment]
Related to #198
