### ISSUE TITLE
load test failure is hidden if import fails in a subpackage

### ISSUE THREAD

**Issue by little-dude** [nose-devs/nose2#259]
Reproducing:

```
mkdir a_subpackage
touch a_subpackage/__init__.py
cat << EOF > a_subpackage/test_foo.py
import doesnotexist
def test_something():
   pass
EOF
nose2 a_subpackage.test_foo
```
output:
```
E
======================================================================
ERROR: a_subpackage.test_foo (nose2.loader.LoadTestsFailure)
----------------------------------------------------------------------
AttributeError: 'module' object has no attribute 'test_foo'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```
Expected:
```
E
======================================================================
ERROR: a_subpackage.test_foo (nose2.loader.LoadTestsFailure)
----------------------------------------------------------------------
ImportError: No module named doesnotexist

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

The workaround, when that happens is to try to import the module directly do get the stacktrace:
```
python -m a_subpackage.test_foo
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/corentih/a_subpackage/test_foo.py", line 1, in <module>
    import doesnotexist
ImportError: No module named doesnotexist
```

The reason of this is in `nose2/utils.py`:

```python
def object_from_name(name, module=None):
    """Import object from ``name``"""
    parts = name.split('.')
    if module is None:
        parts_copy = parts[:]
        while parts_copy:
            try:
                print 'importing {}'.format('.'.join(parts_copy))
                module = __import__('.'.join(parts_copy))
                break
            except ImportError:
                print 'failed'
                del parts_copy[-1]
                if not parts_copy:
                    raise
        parts = parts[1:]

    parent = None
    obj = module
    for part in parts:
        # The "AttributeError" occurs here because the module `a_subpackage` has no attribute `test_foo` since it couldnt be imported
        parent, obj = obj, getattr(obj, part)
    return parent, obj
```

I added a few prints to visualize what happens. Output when running `nose2 a_subpackage.test_foo`:

```
importing a_subpackage.test_foo
failed                            ==> Here we should raise an exception, instead of continuing, but how to determine this is a legit import failure?
importing a_subpackage

E
======================================================================
ERROR: a_subpackage.test_foo (nose2.loader.LoadTestsFailure)
----------------------------------------------------------------------
AttributeError: 'module' object has no attribute 'test_foo'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

I don't really know how to fix that, and it's pretty annoying. I think it relates to https://github.com/nose-devs/nose2/issues/109

@leth any idea? I'm asking because you seem to have looked at how `LoadTestFailure`s are reported, recently (https://github.com/nose-devs/nose2/commit/255074d06ed8f5ad3daaa8ea5ffc5a9f090fb830)

**Comment by leth** [comment]
Nope. I was just fixing a bug I found.
Looking at `object_from_name` I can't see why you'd want it to catch `ImportError` at all.
Can you find a test case where it makes sense to catch it?

**Comment by little-dude** [comment]
I use nose2 to run openstack tests, using tempest. Let's say I have a `openstack/tempest/thirdparty/me/test_netpartitions.py` module that contains some error that makes import fail. If I run it with nose2 I get the followin stacktrace:

```
ERROR   : openstack.tempest.thirdparty.me.test_netpartitions (nose2.loader.LoadTestsFailure): error
Traceback (most recent call last):
  File "env/lib/python2.7/site-packages/unittest2/case.py", line 625, in run
    testMethod()
  File "env/lib/python2.7/site-packages/nose2/loader.py", line 117, in testFailure
    raise exception
AttributeError: 'module' object has no attribute 'test_netpartitions'
```

This does not tell me what's wrong in `test_netpartitions.py`. Actually, it does not even tell me that this failure is due to an import.

With nose, I get a much more useful stacktrace:

```
Traceback (most recent call last):
  File "env/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "env/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "env/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "testsuites/openstack/tempest/thirdparty/me/test_netpartitions.py", line 16, in <module>
    import somethingthatfails
ImportError: No module named somethingthatfails
```

**Comment by leth** [comment]
I understand the problem, I was just suggesting how you might look into it further.

I'm not a maintainer of nose2 I just submit the occasional pull request.

On 13 November 2015 13:31:26 GMT+00:00, little-dude <notifications@github.com> wrote:
>I use nose2 to run openstack tests, using tempest. Let's say I have a
>`openstack/tempest/thirdparty/me/test_netpartitions.py` module that
>contains some error that makes import fail. If I run it with nose2 I
>get the followin stacktrace:
>
>```
>ERROR   : openstack.tempest.thirdparty.me.test_netpartitions
>(nose2.loader.LoadTestsFailure): error
>Traceback (most recent call last):
>File "env/lib/python2.7/site-packages/unittest2/case.py", line 625, in
>run
>    testMethod()
>File "env/lib/python2.7/site-packages/nose2/loader.py", line 117, in
>testFailure
>    raise exception
>AttributeError: 'module' object has no attribute 'test_netpartitions'
>```
>
>This does not tell me what's wrong in `test_netpartitions.py`.
>Actually, it does not even tell me that this failure is due to an
>import.
>
>With nose, I get a much more useful stacktrace:
>
>```
>Traceback (most recent call last):
>File "env/lib/python2.7/site-packages/nose/loader.py", line 413, in
>loadTestsFromName
>    addr.filename, addr.module)
>File "env/lib/python2.7/site-packages/nose/importer.py", line 47, in
>importFromPath
>    return self.importFromDir(dir_path, fqname)
>File "env/lib/python2.7/site-packages/nose/importer.py", line 94, in
>importFromDir
>    mod = load_module(part_fqname, fh, filename, desc)
>File
>"testsuites/openstack/tempest/thirdparty/me/test_netpartitions.py",
>line 16, in <module>
>    import somethingthatfails
>ImportError: No module named somethingthatfails
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/nose-devs/nose2/issues/259#issuecomment-156431914

-- 
Sent from my phone. Please excuse my brevity.

**Comment by little-dude** [comment]
> I'm not a maintainer of nose2 I just submit the occasional pull request.

I know, I asked just in case, because I quite helpless on this and it's been annoying me for a while. Thanks anyway!

**Comment by leth** [comment]
Try this out :)

```python
def object_from_name(name, module=None):
    """Import object from ``name``"""
    import_error = None
    parts = name.split('.')
    if module is None:
        parts_copy = parts[:]
        while parts_copy:
            try:
                module = __import__('.'.join(parts_copy))
                break
            except ImportError as import_error:
                del parts_copy[-1]
                if not parts_copy:
                    raise
        parts = parts[1:]

    parent = None
    obj = module
    for part in parts:
        try:
            parent, obj = obj, getattr(obj, part)
        except AttributeError
            if import_error:
                # Re-raise the import error which got us here, since
                # it probably better describes the issue
                raise import_error
            raise
        else:
            # If the getattr passed, it's no longer appropriate to re-raise
            # the import error
            import_error = None
    return parent, obj
```

**Comment by leth** [comment]
Did that do the trick @little-dude?

**Comment by little-dude** [comment]
Sorry I just saw the notifications. Thanks a lot! I'm going to try this tonight :D

**Comment by little-dude** [comment]
@leth it does the trick indeed, even in more complex cases!

Of course it's still not as smart as nose, because it raises an `ImportError` instead of an `AttributeError` in such cases:

```python
# mymodule.py

def test_foo():
    pass
```

nose2:

```
$ nosetests mymodule.test_foo
E
======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'test_foo')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/me/env/lib/python2.7/site-packages/nose/loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "/home/me/env/lib/python2.7/site-packages/nose/util.py", line 322, in resolve_name
    obj = getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_foo'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

$  nose2 mymodule.test_foo
E
======================================================================
ERROR: mymodule.test_foo (nose2.loader.LoadTestsFailure)
----------------------------------------------------------------------
ImportError: No module named test_foo

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

But anyway, it's still perfectly understandable, so I think it's much better this way.

Thanks a lot, as I said, it's been annoying me for a while :+1:
