### ISSUE TITLE
Release a new version on pypi

### ISSUE THREAD

**Issue by little-dude** [nose-devs/nose2#263]
I'd like to make a release since there have been a few changes since 0.5.0 (https://github.com/nose-devs/nose2/releases/tag/0.5.0). See also: https://github.com/nose-devs/nose2/issues/253

I'd just like to review the changes and write a changelog and update the authors file. List of commits since 0.5.0

15466b3f65a37ef9bf22074e6b5d532226750fec Looking for maintainers.
1925daec7b24266c7b3d3a7ca5988ef3aefe7caf Merge pull request #258 from little-dude/loglevel
b4d5caa28bd0c2a40da5c83f14874e35f263704a Merge pull request #257 from leth/travis_tweaks
78e1dac6bdddfb2fd040000830d213d5af68c0ef change loglevel to error for internal errors
88ea394d638f602686019e42c61d7dd7f273c292 remove logging
a583d91214ac2f741efbe310e96eb54503732373 Add pip caching to travis build
a2e601ac34a963626c4805bcb74a98f4487c6458 Use containers for travis build
d933502929e6bcac32fe50d76d425e1c95a46a09 Merge pull request #256 from leth/patch-2
fbdd2156d9a826c77c06989ec0070894434f5c6d Don't use coverage on py3.2 travis build
4b630e8223f178ad25eef0e2ecf31f838445d2a0 Disable coverage test on python3.2
d02057dd6f99b5904b8a9659f946dd12936544e6 Merge pull request #255 from leth/patch-1
275c39faa02dc0bd4f8b9d9bd2a012eaee12a338 Fix regex matching coverage output
255074d06ed8f5ad3daaa8ea5ffc5a9f090fb830 Pass caught exception to failedLoadTests
17de000928a2a2ae16760639e33b982c308a2af3 Merge pull request #247 from little-dude/collect
61fc6bc84eac94d737b96ccc9e815638a8bd143b Fix collect plugin for Layers
a83d780c836692e51e93a4699b50097ae66770ff Merge pull request #245 from dlax/generator-exception
cf7c4527caa099c53232e8b0cc39478455538286 Add unit tests for loader's _makeFailedTest method
79307722e58a6a5c62f1b8b06afd375c58e84a2a Merge pull request #244 from leth/coverage_import_time
3454e1e766207a849aeefbac3c478851680e0a06 Merge pull request #243 from mitya57/master
cf408d020fc661daf21553b17804a0fd3a77bf51 Merge pull request #246 from little-dude/setupfix
1459515d2237c01b8e5eab3bf0f3d75c001d4e3c call setUpTest safely
19571d34374026649783ff57289dd4a9c6bdf028 Restore exception context when passed in loader's _makeFailedTest method
268371d815fb319bda4489da9756843204354eab Move plugin hooks to get import-time coverage data
b9e91a6846ee2dab05ebf6d0e8291ed5c3c897d4 Add createdTestSuite hook after test are loaded
b0083d6fea4e77fe511d6cc462cb18ebdbb8e39a Fix the last paragraph in docs/differences.rst
bf9945309d5118ad4723619452c486593964d1b8 Merge pull request #241 from nikolas/patch-1
9284c00bdc39f6324e659aafc382e86b4d722dde Fix typo in README: encourging -> encouraging
56fe2fe116a0fa6b0dc4962fce3eb710b6ba8c83 Merge pull request #240 from Zearin/docs
a7be0299fca451ec5ac8f84231b107be7191886c Fix `:role:` typo
bae2937161d7483dcf99459a8a72b39ebcc9f726 Tweak docstrings under `nose2/`
9afc928c54a5318a5bcadd84ce0ffa725d78268d Merge pull request #239 from Zearin/docs
798f5992305358489f90b77a5d0d2c0d3836a168 Minor markup tweaks to docs
153163adc24806d251b11f59b26bc8f69c6ac415 Merge pull request #236 from alunduil/add-docs-to-sdist
200742b06ae53ca6d55c85fb1af5554b78cafdd1 add missing Makefile for docs in sdist
1100cec5bb7fbc9ae93aa38e099df5a6271536ff Merge pull request #230 from kurniliya/sphinx-build-failure
e08e5de5e3674072a4b218d9aa2db0c79822a239 Merge pull request #234 from silverstripesoftware/233-setuptools-layers
b07f6cb57ed4eabe67917b09a5413122bb1b5fb9 Fixed setuptools to work with Layers
5df9a70fe7089b49f42e5ac38a88847b0ba48473 Merge pull request #232 from kurniliya/loading-from-package
6d879f9ed94e15d3389dd767b8b293b4a4941b73 Unit test for util.ensure_importable.
ffc00062ac6cf8be3e7babba69c3a86a2631a453 Fixes #161
90b11a5e7f7f14e8e89c42e071b4ea5dbc9ccd85 Functional tests.
86114dc0dfa0e43a4abdc53a7f36f59358543fb9 Fixes #230: error in sphinx build
dea5854cb40f1327989933004a8835e3766b33fd Merge pull request #229 from kurniliya/issue_229
f35c04886cac91c70e5d637fc4042042111f3ec9 Fixes #229: Make tests pass on Windows
b53b1b067681434a90a09832834fc6e54a46b569 Merge pull request #222 from dnozay/junitprop
766421974e0fc3c475a82d6f1340963f808d7140 Fixes #224.
64b78ff627b45870c623c1a8344fbdfb30a3b747 Add support for properties in junit xml.
11d601db39bb4eab7f326a1a49b639d05ebf2298 Merge pull request #223 from dnozay/pypy3
e59555695de93a9b7ee1f62814087af1a52655d0 add missing requirements-pypy3.txt
00989f5c7ec820cb3364b28a9701edbf4f3d073e Added the landscape.io badge.

@nose-devs/nose2 what versioning logic are you following? Should this one just be 0.6.0?

**Comment by thedrow** [comment]
SemVer.
0.6.0 should be fine.

**Comment by little-dude** [comment]
thanks.
everything seems ready: https://github.com/nose-devs/nose2/pull/264
I never did a release on python.pypi.org so just to make sure:

- I tag the "bump version commit" and push it
- register the 0.6.0 package: `python setup.py register`
- upload it: `python setup.py sdist upload`

**Comment by thedrow** [comment]
You can bump and tag. Travis should do the rest.

**Comment by little-dude** [comment]
Some authentication error when uploading:
```Uploading nose2-0.6.0.tar.gz

/home/travis/virtualenv/pypy-2.5.0/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.

  SNIMissingWarning

/home/travis/virtualenv/pypy-2.5.0/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

  InsecurePlatformWarning

HTTPError: 401 Client Error: You must be identified to edit package information for url: https://pypi.python.org/pypi```

Maybe @jpellerin credentials changed since last time. I'll try with mine.

**Comment by thedrow** [comment]
:+1: Make sure to encrypt your password.

**Comment by little-dude** [comment]
Still not working. Maybe @jpellerin needs to add me as package maintainer on pypi ?
```
Package Index Owner: jpellerin
Package Index Maintainer: the_drow, kumar303 
```

**Comment by thedrow** [comment]
Yeh probably.

**Comment by little-dude** [comment]
@jpellerin, could you add me as a maintainer on pypi please? My username is "little-dude".

**Comment by little-dude** [comment]
@thedrow would you mind putting your credentials the time @jpellerin give me permissions on pypi please? I'd like to work on a few PRs but it would be nice to make a release first.

**Comment by thedrow** [comment]
yeh sure.

**Comment by thedrow** [comment]
Done.

**Comment by little-dude** [comment]
phew, nose2 0.6.0 is on pypi :) thanks a lot!
