### ISSUE TITLE
junit-xml always add logs in system_err

### ISSUE THREAD

**Issue by slemesle** [nose-devs/nose2#266]
This is really strange because logs are typically not outputted in stderr. 
In nosetests we did not have logs in case of successful test but now they are always displayed as system_err. 

May it be possible to output them in system_out instead ?

In the testOutcome handler just replace system_err with this code ...

```python
        system_out = ET.SubElement(testcase, 'system-out')
        system_out.text = string_cleanup(
            '\n'.join(event.metadata.get('logs', '')),
            self.keep_restricted
        )

```

**Comment by little-dude** [comment]
This is weird indeed. However it seems to be on purpose, and some unit tests actually check this behavior. I'm not using this plugin, so give me some time to understand, and see what we can do.

**Comment by slemesle** [comment]
ok I'll wait for your updates. 
Here is a link to an explained XML Schema for Junit xml reports.
http://help.catchsoftware.com/display/ET/JUnit+Format

**Comment by little-dude** [comment]
Hi @slemesle, this issue is more complexe than I thought. By default, `nose2` output gets printed on stderr.

```python
# a.py
from __future__ import print_function
import sys

def test_out():
    print('hello stdout!', file=sys.stdout)

def test_err():
    print('hello stderr!', file=sys.stderr)
```
running this with `nose2 a --verbose >out.txt 2> err.txt`:

```
# out.txt
hello stdout!
````

```
# err.txt
a.FunctionTestCase (test_err) ... hello stderr!
ok
a.FunctionTestCase (test_out) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.001s

OK
```

I assume the idea is to be able to separate your tests output and the framework output. It is quite easy to change:

```
diff --git a/nose2/plugins/result.py b/nose2/plugins/result.py
index f9637df..25b39c5 100644
--- a/nose2/plugins/result.py
+++ b/nose2/plugins/result.py
@@ -51,7 +51,7 @@ class ResultReporter(events.Plugin):
         self.dontReport = set(['errors', 'failures', 'skipped', 'passed',
                                'expectedFailures', 'unexpectedSuccesses'])

-        self.stream = util._WritelnDecorator(sys.stderr)
+        self.stream = util._WritelnDecorator(sys.stdout)
         self.descriptions = self.config.as_bool('descriptions', True)

     def startTest(self, event):
```

but all the tests need to be changed as well.

**Comment by slemesle** [comment]
No the idea is to get the logs output in the junit report at the good place. 
I use Jenkins to automate tests and my wish is to be able to view complete logs of the tests failed or not. 

So I don't see the exact relation with the log capture I wish to have. So my point is just about logs capture.

**Comment by little-dude** [comment]
@slemesle this will be part of `0.7.0` release. I'm planning to release it later in march. Sorry it took so long.
