### ISSUE TITLE
update documentation on readthedoc

### ISSUE THREAD

**Issue by little-dude** [nose-devs/nose2#272]
@thedrow @jpellerin, how can I update the documentation on readthedoc? It's still 0.4.7 documentation, and I'd like to update it. Apparently there webhooks for github, but I don't have permissions to see/change the repo settings.

**Comment by thedrow** [comment]
I don't either.
Only @jpellerin has.

**Comment by jpellerin** [comment]
Any better now?

**Comment by little-dude** [comment]
Yes! Thank you!

**Comment by thedrow** [comment]
@jpellerin Care to grant @little-dude the permissions to do what ever is needed with this repo?

**Comment by little-dude** [comment]
It seems that I triggered a build on readthedoc when adding the readthedoc hook... Now we have the documentation for the master branch in place, but some things do not apply to 0.6.x. I'd like to add a 0.6.x version on readthedoc but I guess @jpellerin you need to give me the permissions again.

**Comment by little-dude** [comment]
The main difference are the events and hooks I added in master recently: https://github.com/little-dude/nose2/commit/21e89f73a9858490d6dec39ee648ac34f22f6c21

**Comment by katrinabrock** [comment]
This seems to either resolved or if it is still broken, I will see it and get to it next time I do a doc update.
