### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by brianmay** [nose-devs/nose2#273]
11 tests fail for the latest release using Python 2.7 from Debian/unstable.

Unless fixed, this means nose2 and everything that depends on nose2 will get removed from Debian.

Example:

```
======================================================================
FAIL: test_failure_to_read_empty_properties (nose2.tests.functional.test_junitxml_plugin.JunitXmlPluginFunctionalFailureTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nose2/tests/functional/test_junitxml_plugin.py", line 167, in test_failure_to_read_empty_properties
    "'.*%s'" % filename_for_regex)
  File "nose2/tests/_common.py", line 64, in assertTestRunOutputMatches
    testf(util.safe_decode(cmd_stderr), stderr)
AssertionError: Regexp didn't match: "Internal Error: runTests aborted: JUnitXML: could not decode file: '.*empty_properties/properties.json'" not found in u"test (test_junitxml_empty_properties.Test) ... ok\nInternal Error: runTests aborted: [Errno 2] JUnitXML: Properties file does not exist: '/home/brian/tree/debian/python-modules/nose2/nose2/tests/functional/support/scenario/junitxml/empty_properties/properties.json'\n"

```

**Comment by little-dude** [comment]
@brianmay sorry about this. All the tests were passing on CI. I'm looking into it.

**Comment by brianmay** [comment]
I am also getting 5 failures running directly from master. I won't provide the output here, it is very verbose, however I can provide more details if required (for example if I have done something wrong). Am running the tests with:

```
python -m nose2.__main__
```

Probably need to double check this is correct, when I am more awake.

**Comment by little-dude** [comment]
For the tests you need to install `mock`. It is not listed in the requirements.txt because it's needed only for the tests.

After installing mock, I'm down to one failing test, (`nose2.tests.functional.test_main.TestPluggableTestProgram.test_run_in_module_from_its_main`) with this stacktrace:

```
Traceback (most recent call last):
  File "nose2/tests/functional/test_main.py", line 27, in test_run_in_module_from_its_main
    self.assertTestRunOutputMatches(proc, stderr='Ran 1 test')
  File "nose2/tests/_common.py", line 64, in assertTestRunOutputMatches
    testf(util.safe_decode(cmd_stderr), stderr)
AssertionError: Regexp didn't match: 'Ran 1 test' not found in u'Traceback (most recent call last):\n  File "/home/corentih/tmp/nose2/nose2/tests/functional/support/scenario/one_test/tests.py", line 1, in <module>\n    import nose2\nImportError: No module named nose2\n'
```

Weirdly, this test does `import nose2`, so you need to install it. After installing it, I have no more failure.

**Comment by little-dude** [comment]
I uploaded `0.6.1`. Just tested locally and tests are passing for python27 :)

**Comment by brianmay** [comment]
Still one test failure - my fault???

```
======================================================================
FAIL: test_run (nose2.tests.functional.test_coverage.TestCoverage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nose2/tests/functional/test_coverage.py", line 24, in test_run
    stderr=os.path.join('lib', 'mod1.py').replace('\\', r'\\') + STATS)
  File "nose2/tests/_common.py", line 64, in assertTestRunOutputMatches
    testf(util.safe_decode(cmd_stderr), stderr)
AssertionError: Regexp didn't match: 'lib/mod1.py           8      5    38%' not found in u'test1 (test_coverage.TestLib) ... ok\n\n----------------------------------------------------------------------\nRan 1 test in 0.001s\n\nOK\n---------- coverage: platform linux2, python 2.7.11-final-0 ----------\nName           Stmts   Miss  Cover\n----------------------------------\nlib/__init__       0      0   100%\nlib/mod1           8      5    38%\n----------------------------------\nTOTAL              8      5    38%\n'

```

**Comment by little-dude** [comment]
@brianmay this is because you are not using the latest `coverage` library: https://github.com/nose-devs/nose2/commit/275c39faa02dc0bd4f8b9d9bd2a012eaee12a338

For the record here is what I'm using:

```
cov-core==1.15.0
coverage==4.0.3
```

I'm going to make the test a little bit less strict and upload a `0.6.2`

**Comment by brianmay** [comment]
Latest version in git passes tests. Think you already have released version 0.6.2 however - probably will need to release version 0.6.3

**Comment by little-dude** [comment]
No, 0.6.2 contains the fix for the failing test (`nose2.tests.functional.test_coverage.TestCoverage`), it should work for you.

**Comment by little-dude** [comment]
here is the corresponding pr: https://github.com/nose-devs/nose2/pull/275

**Comment by brianmay** [comment]
I think the 0.6.2 tag might be on the wrong git commit, which was confusing me.

**Comment by brianmay** [comment]
Same with the 0.6.1 tag too.

**Comment by brianmay** [comment]
Hmmm. Possibly you have force updated these tags, which means I will have the wrong values on my checked out version.

**Comment by brianmay** [comment]
Deleted the tags, and refetched; looks ok now.

**Comment by little-dude** [comment]
>  Possibly you have force updated these tags
Oops sorry :S This was my first release, and I kind of messed up, so yeah, I deleted the previous 0.6.2 tag...

I'm closing since it seems to work now :) Thanks for the report and the regular updates!

**Comment by warsaw** [comment]
@brianmay Thanks for updating the Debian package's git vcs, however I'm still seeing 10 test failures with Python 3.5.  I don't see them in upstream's git so I'll try to figure out which commit fixes the remaining problem.

**Comment by little-dude** [comment]
@warsaw I added python 3.5 support to the master branch only. I can add python 3.5 support in the 0.6.x branch as well and make a 0.6.3 release if you want.

**Comment by brianmay** [comment]
@little-dude If you could make a 0.6.3 release with the fixes, this would be very much appreciated, and would enable us to fix nose2 (and all the packages that depend on nose2) in Debian. Thanks.

**Comment by little-dude** [comment]
It's late here so I'll try to do it tomorrow.
Just to be clear: only python 3.5 is broken with 0.6.2, right?
I guess this issue is tracked somewhere, would you mind posting the link to the bug tracker?

**Comment by warsaw** [comment]
@little-dude Yes.  In the current in-development versions of both Debian and Ubuntu, we have only Python 2.7 and 3.5, and 2.7 is already fine.  So a nose2 0.6.3 with Python 3.5 support would be wonderful.  @brianmay Once upstream 0.6.3 is released, feel free to do a team upload of nose2 if you want.  I'm also fine if you just want to update the git repo and have me do the upload.  Just let me know!

**Comment by little-dude** [comment]
I'll try to fix that tonight.

**Comment by little-dude** [comment]
@brianmay @warsaw python 3.5 tests passed fr me and on travis https://github.com/nose-devs/nose2/pull/271
I just released 0.6.3, please let me know if it fixes all your tests for debian.

**Comment by little-dude** [comment]
sorry, the PR is this one: https://github.com/nose-devs/nose2/pull/283

**Comment by brianmay** [comment]
Thanks. Just testing it now.

**Comment by little-dude** [comment]
*crossing fingers*

**Comment by brianmay** [comment]
That looks a lot better now. Thanks.

**Comment by little-dude** [comment]
Cool. Closing then.
