### ISSUE TITLE
Suggested change to docs - how to do .ini/.cfg keys as lists

### ISSUE THREAD

**Issue by devdave** [nose-devs/nose2#290]
Had to do a trial by error to figure out how to have coverage-report do both term-missing & html.

Perhaps adding an example for proper config values would help someone else out?

Did the following until I figured it out.

```
;coverage-report = [term-missing,html]
; ['[term-missing,html]']

;coverage-report = term-missing, html
;['term-missing, html']

;coverage-report = term-missing html
; ['term-missing html']

;coverage-report: term-missing
;html
; exception, config parse error "\nthtml"

coverage-report =   term-missing
                    html
; This worked
```

**Comment by little-dude** [comment]
Good idea. I'll add it this weekend.

**Comment by devdave** [comment]
If you want, I can fork the repo and send you back a merge request?  Perhaps just make it as an appended example for just that config value?

**Comment by katrinabrock** [comment]
If you are still willing to do a PR for this doc fix, please do.

**Comment by devdave** [comment]
Will do; may take me around a week as I need to pull the project related to this issue, update nose2, and then rebuild the docs locally to sanity check.

**Comment by katrinabrock** [comment]
Great! If you're feeling charitable, there's a few other doc related fixes, some are quite simple:
https://github.com/nose-devs/nose2/labels/docs

**Comment by devdave** [comment]
Given what I discovered above, moving to close the issue I raised.
