### ISSUE TITLE
How I can use xunit like nose?

### ISSUE THREAD

**Issue by ryukinix** [nose-devs/nose2#293]
I search in the docs something about `xunit` and only what I found is about some implementation in #18 

In nosetests I can do:
`nosetests --with-xunit --xunit-file=shippable/testresults/nosetests.xml`

Exists something equivalent here?

**Comment by little-dude** [comment]
Hi,

What exactly is the difference between xunit and junit outputs? The junit plugin is documented here if you want to give it a try: http://nose2.readthedocs.io/en/latest/plugins/junitxml.html

**Comment by ryukinix** [comment]
I think is the same, but the docs is not very clear for me how I can get the similar output above. You can, please, give me a example?

**Comment by aleb** [comment]
It is awkward enabling and configuring the xunit plugin, since you have to use a configure file. You have to use `nose2 --plugin nose2.plugins.junitxml --config myconfig.cfg` and in myconfig.cfg: 
```
[junit-xml]
always-on = True
path = /path/to/output.xunit
```

See https://github.com/pitivi/pitivi/blob/master/tests/meson.build for an example.
