### ISSUE TITLE
Add version information to module

### ISSUE THREAD

**Issue by mairsbw** [nose-devs/nose2#297]
It's helpful when checking dependencies programmatically or for a developer to be able to retrieve version information from the modules `__version__` attribute (see [PEP396](https://www.python.org/dev/peps/pep-0396/)).

Our use case is a `check_dependencies.py` script that the developer can run to verify they have all necessary packages installed and that they're the correct version.

**Comment by mairsbw** [comment]
Looks resolved, thanks!

**Comment by little-dude** [comment]
Thank you for reporting :)
0.6.5 is now on pypi, and has the fix:
```
>>> import nose2
>>> nose2.__version__
'0.6.5'
```
