### ISSUE TITLE
Nose2 not compatible with setuptools develop mode

### ISSUE THREAD

**Issue by ejstrates** [nose-devs/nose2#313]
When a package is installed in develop mode, nose2 is unable to import test modules

Could be related to issue #250

**Comment by katrinabrock** [comment]
dup of https://github.com/nose-devs/nose2/issues/214 ?

**Comment by sirosen** [comment]
I'm closing this as a duplicate. There's insufficient detail here to attempt to reproduce (especially given how old it is), and #214 is a more complete description on the assumption that the two are the same.
