### ISSUE TITLE
Rerun easily from the command line a specific failed test

### ISSUE THREAD

**Issue by aleb** [nose-devs/nose2#315]
If I run the tests and some fail, I want to pick one and run only that one, until it's fixed. For example initially there are a few broken tests:
```
$ nose2 tests
...
ERROR: testVersionInfo (tests.test_application.TestPitivi)
...
FAIL: testExisting (tests.test_misc.BinarySearchTest)
```
Then to run only testVersionInfo, I have to build up the argument for the command line:
```
$ nose2 tests.test_application.TestPitivi.testVersionInfo
```

It would be easier to have the message printed like this:
```
ERROR: tests.test_application.TestPitivi.testVersionInfo
...
FAIL: tests.test_misc.BinarySearchTest.testExisting
```
This would allow quick copy/pasting.

Also nice would be tab completion. :)

**Comment by katrinabrock** [comment]
Would accept a PR for tab completion.

I'm very hesitant to change output formatting because other users have built parsers for nose2 output and this change would likely break their workflow. (see #254 and #198 )
