### ISSUE TITLE
Coverage plugin does not work with "setup.py test"

### ISSUE THREAD

**Issue by CausticYarn** [nose-devs/nose2#317]
I am trying to use "python setup.py test" to run unit tests and get a coverage report. I have set the `test_suite` argument to the `setup` method to `nose2.collector.collector`, and configured a nose2.cfg file with the following:

`[coverage]`
`always-on = True`
`coverage-report = xml`

When I run "nose2" from the command line, it runs the coverage and outputs the coverage.xml file, but when I run it from setup.py, it ignores the coverage section. I can tell it's responding to the nose2.cfg file because if I add junit-xml configuration, it works using both methods, but coverage only seems to work via the nose2 command line.

**Comment by shaoshu2** [comment]
I encountered with the same bug as well. Expecting a fix or at least an estimation of timeline.

**Comment by shaoshu2** [comment]
BTW Sirosen, may I ask whether there is a work around to make coverage plugin work from setuptools?

**Comment by sirosen** [comment]
Travis has been failing due to what looks to me like an unrelated issue, which has blocked the release of a fix (#366 makes it work). I haven't had time to try to dig into it lately, but I can try to carve out some time this weekend.

I'll also open an issue to track the blocking problem.
