### ISSUE TITLE
Strict unittest dependency causes version conflicts

### ISSUE THREAD

**Issue by CausticYarn** [nose-devs/nose2#318]
I am trying to use Nose2 to test code on Python 2.6.  Its strict dependency on unittest2 between 0.5.1 and 0.6 is causing version conflicts for other testing tools (e.g. mox, which requires unittest>=1.0.0).

Is this a true requirement or is it possible to use Nose2 successfully with unittest2 > 0.6?

**Comment by katrinabrock** [comment]
> I am trying to use Nose2 to test code on Python 2.6. Its strict dependency on unittest2 between 0.5.1 and 0.6 is causing version conflicts for other testing tools (e.g. mox, which requires unittest>=1.0.0).

We will not support 2.6 in future releases.

> Is this a true requirement or is it possible to use Nose2 successfully with unittest2 > 0.6?

I don't know. Sorry this went unanswered for so long. Hope you were able to put something together that worked for you
