### ISSUE TITLE
No easy way to define and utilize a reusable layer (with tests) in Such

### ISSUE THREAD

**Issue by SalmonMode** [nose-devs/nose2#324]
I've been digging around the source code and haven't been able to find a clean way to define a labelled section of layers, sublayers, and tests that I can reuse in multiple places (although, I may have missed it). I'm currently trying to write some functional tests for a website, and at many points, I'll have to run the same exact tests, so being able to define those layers ahead of time and just drop them in wherever they need to be would be incredibly useful.

Ideally, I'd like to have something like this be spat out:

```
MainPage
  NavigationBar
    AboutUsLink
      displayed ... ok
    SubMenu
      Default
        MenuItem1Link
          not displayed ... ok
      Expanded
        MenuItem1Link
          displayed ... ok
OtherPage
  NavigationBar
    AboutUsLink
      displayed ... ok
    SubMenu
      Default
        MenuItem1Link
          not displayed ... ok
      Expanded
        MenuItem1Link
          displayed ... ok
```

where `NavigationBar` is a collection of layers, sublayers, and tests that is being reused in both `MainPage` and `OtherPage`.

I've tried a number of methods, but nothing seems to be working. Is there a way to do this? And if not, maybe this is a good opportunity to increase the flexibility of `Such`.

**Comment by sirosen** [comment]
Such can do this. I'm not sure what more support could be added to the plugin?
Suggest closing as a wontfix or merely documenting how to do this.

Consider this example:

```python
def navigation_tests(it):
    with it.having('NavigationBar'):
        @it.has_setup
        def nav_setup():
            it.nav_bar = True

        @it.has_teardown
        def nav_teardown():
            del it.nav_bar

        @it.should('have a nav bar')
        def test_has_nav():
            assert it.nav_bar


with such.A('web application') as it:
    with it.having('MainPage'):
        @it.has_setup
        def setup_main_page():
            it.title = 'main'

        @it.has_teardown
        def teardown_main_page():
            del it.title

        @it.should('have the right title')
        def good_title():
            assert it.title == 'main'

        navigation_tests(it)

    with it.having('OtherPage'):
        navigation_tests(it)
```

produces this output:

```
A web application
  having MainPage
    should have the right title ... ok
    having NavigationBar
      should have a nav bar ... ok
  having OtherPage
    having NavigationBar
      should have a nav bar ... ok
```

**Comment by katrinabrock** [comment]
@SalmonMode actually made a plugin to fix their usecase: https://github.com/salmonmode/contextional
