### ISSUE TITLE
Layer-reporter does not indent docstring 

### ISSUE THREAD

**Issue by cmar81** [nose-devs/nose2#327]
Given a test
def test_mymethond(self):
    """what this does

   hi there
   """

nose2 will output 'what this does' when the test is run, but the text will not be indented to reflect the layers used. 

Result of test run: 
TopLayer
&nbsp;&nbsp;SecondLayer
&nbsp;&nbsp;&nbsp;&nbsp;test_find_unassigned_signals (test_wrapper.SecondLayerTests) ... ok
&nbsp;&nbsp;&nbsp;&nbsp;test_no_newer_definitions (test_wrapper.SecondLayerTests)
Test that versions in API Wrapper are the latest ... ok
&nbsp;&nbsp;&nbsp;&nbsp;test_only_add_customer_once (test_wrapper.SecondLayerTests) ... ok
&nbsp;&nbsp;&nbsp;&nbsp;test_only_one_parquet_file_pr_customer (test_wrapper.SecondLayerTests) ... ok

Expected:
TopLayer
&nbsp;&nbsp;SecondLayer
&nbsp;&nbsp;&nbsp;&nbsp;test_find_unassigned_signals (test_wrapper.SecondLayerTests) ... ok
&nbsp;&nbsp;&nbsp;&nbsp;test_no_newer_definitions (test_wrapper.SecondLayerTests)
&nbsp;&nbsp;&nbsp;&nbsp;Test that versions in API Wrapper are the latest ... ok
&nbsp;&nbsp;&nbsp;&nbsp;test_only_add_customer_once (test_wrapper.SecondLayerTests) ... ok
&nbsp;&nbsp;&nbsp;&nbsp;test_only_one_parquet_file_pr_customer (test_wrapper.SecondLayerTests) ... ok

or maybe even
TopLayer
&nbsp;&nbsp;SecondLayer
&nbsp;&nbsp;&nbsp;&nbsp;test_find_unassigned_signals (test_wrapper.SecondLayerTests) ... ok
&nbsp;&nbsp;&nbsp;&nbsp;Test that versions in API Wrapper are the latest (test_wrapper.SecondLayerTests) ... ok
&nbsp;&nbsp;&nbsp;&nbsp;test_only_add_customer_once (test_wrapper.SecondLayerTests) ... ok
&nbsp;&nbsp;&nbsp;&nbsp;test_only_one_parquet_file_pr_customer (test_wrapper.SecondLayerTests) ... ok

**Comment by artragis** [comment]
I can take this one.

**Comment by artragis** [comment]
So, after investigating, the issue is due to the `Result` object. 

In `nose2.plugins.result.py` you find : 

```python

    def _getDescription(self, test, errorList):
        if not isinstance(test, unittest.TestCase):
            return test.__class__.__name__
        doc_first_line = test.shortDescription()
        if self.descriptions and doc_first_line:
            desc = '\n'.join((str(test), doc_first_line))
        else:
            desc = str(test)
        event = events.DescribeTestEvent(
            test, description=desc, errorList=errorList)
        self.session.hooks.describeTest(event)
        return event.description
```

the indentation issue comes from `desc = '\n'.join((str(test), doc_first_line))`. 

I commit a fix as soon as possible.
