### ISSUE TITLE
Is there any plugins support openlava or lsf

### ISSUE THREAD

**Issue by shady831213** [nose-devs/nose2#328]
Hi,
Is there any plugins support openlava or lsf?
Best Regards

**Comment by sirosen** [comment]
There are no plugins which support any job scheduling systems, be it OpenLava, Condor, or anything else. You are, of course, free to write one, but I wouldn't want it to be a built-in plugin as part of the nose2 source.

Trying to distribute jobs from the testrunner seems like doing it the wrong way around. You can distribute testing jobs, and use nose2 to discover and run tests for those jobs.

I'm going to close this.
