### ISSUE TITLE
Documentation of plugins is unclear: What is the "module name"

### ISSUE THREAD

**Issue by Bernhard10** [nose-devs/nose2#329]
For the plugins that are not loaded by default, the documentation says: "add the plugin module name to the plugins list in a config file’s [unittest] section". 
To avoid confusion, it would be nice to explicitly state that this module name is dot-seperated starting with `nose2`.

Further more, the individual plugin sections could have the module name somehow highlighted at the beginning (people don't read the docs from start to end)

In the case of "profiler", I tried "profiler" and "prof" before I finally tried "nose2.plugins.prof".

(The first two of course gave the error `ImportError: No module named profiler` and `ImportError: No module named prof` respectively)

**Comment by katrinabrock** [comment]
Thanks for letting us know. Would accept a PR.

**Comment by katrinabrock** [comment]
fixed, by above, thanks!
