### ISSUE TITLE
Does nose2 plan to support running tests via regular expression?

### ISSUE THREAD

**Issue by peter-wangxu** [nose-devs/nose2#332]
I met a issue when using nose2 via regex, for example, run tests which starts with `test_put`

```python
~/persist-queue$ nose2 -v test_put
test_put (nose2.loader.LoadTestsFailure) ... ERROR

======================================================================
ERROR: test_put (nose2.loader.LoadTestsFailure)
----------------------------------------------------------------------
ImportError: No module named test_put

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

```

there should be 5 tests via this regexp.

Thanks
Peter

**Comment by katrinabrock** [comment]
We currently don't support this behavior and it is not in immediate plans to. Would accept a PR to add this functionality. Default should be still be to exactly match test names, a flag could indicate to match as regex instead.
