### ISSUE TITLE
Automatically install per-python version requirements with `pip install nose2`

### ISSUE THREAD

**Issue by katrinabrock** [nose-devs/nose2#344]
As far as I can tell, today `pip install nose2` only installs requirements in requirements.txt even if there are additional requirements for the version of python running in `requirements-x.y.txt`. Looks like these additional requirements are installed by-hand in travis: https://github.com/nose-devs/nose2/blob/master/.travis.yml#L14 , should be done in setup.py. We are already checking the version in setup.py, might as well use it for this. https://github.com/nose-devs/nose2/blob/master/setup.py#L55

**Comment by katrinabrock** [comment]
This causes tox to fail.

**Comment by artragis** [comment]
Hello, I can help you with that.

**Comment by katrinabrock** [comment]
Merged too soon, still some outstanding issues.

**Comment by katrinabrock** [comment]
Fixed with https://github.com/nose-devs/nose2/pull/350 . Thanks for your contribution!
