### ISSUE TITLE
Get rid of bootstrap.sh (?); maybe add Makefile

### ISSUE THREAD

**Issue by sirosen** [nose-devs/nose2#358]
Working on #357 made me take notice of this script. As far as I can tell, it's a script which invokes... `python setup.py develop`
The rest of it is window dressing. There's no need to call `pip` explicitly since setuptools handles the dependencies, it doesn't actually install sphinx dependencies, and forcing the use of virtualenvwrapper is unnecessary (plain virtualenv works just fine).

I think it should be removed.

---

If there is to be any workflow automation, I would advocate for a makefile with the following targets:
- `make help`: echo each target with description
- `make develop`: create virtualenv, `setup.py develop`, install `docs-requirements.txt`, install `tox`
- `make docs`: submake to run sphinx
- `make test`: invoke `tox`

None of this is necessary, of course, but it beats the pants off of a script that does only one part of this and does it poorly.

This big selling point for this is that someone new to the project can run `make test`, and have that install everything and run `tox` for them.

**Comment by katrinabrock** [comment]
I don't think this script adds much value, I'd be fine with getting rid of it and any references to it.

**Comment by katrinabrock** [comment]
This is mostly done, would still like this to be tested in travis somehow so we know if we break it w/o testing locally.

**Comment by sirosen** [comment]
I just spent a few minutes trying to work out what reasonable Travis config for testing this looks like, and it seems like it wouldn't be worth the additional complexity.

The Makefile assumes you want to construct a new virtualenv for tox installation, whereas all Travis python runs happen within a virtualenv already. Disentangling things would require significantly more stuff get added the Makefile, which is quite short at present.

I think locally testing changes to the Makefile is a perfectly acceptable arrangement -- it's not like it should be changing on a daily basis anyway.
