### ISSUE TITLE
Get coverage report in 0.7.0

### ISSUE THREAD

**Issue by IceflowRE** [nose-devs/nose2#362]
With 0.7.0 the `.coverage` file gets not generate anymore?

`nose2 -c setup.cfg -v`

My setup.cfg
```
[unittest]
code-directories = code
test-file-pattern = *_test.py

[output-buffer]
always-on = True
stderr = False
stdout = True

[coverage]
always-on = True
coverage = code
```

The https://nose2.readthedocs.io/en/latest/plugins/coverage.html documentation doesnt get updated too, as the `coverage-plugin` is not provided.

**Comment by katrinabrock** [comment]
@sirosen ?

**Comment by sirosen** [comment]
Hi @IceflowRE, sorry about the trouble. There are two issues:

One is simple documentation. It should read `nose2[coverage_plugin]`, not `nose2[coverage-plugin]`.

The other bug, unfortunately, doesn't have an easy workaround. I've put together a fix for it, but it will require a new release of `nose2` to get the fixed behavior.

In the meantime, you can use the `coverage` command to run `nose2` tests, as in `coverage run -m nose2 -c setup.cfg -v`.
Of course, installing `nose2[coverage_plugin]==0.6.5` will also work, assuming you don't want or need any of the changes between `0.6.5` and `0.7.0` until this is fixed.

**Comment by katrinabrock** [comment]
> it will require a new release of nose2 to get the fixed behavior. 

Now that I know how to do it, I'm fine doing weekly releases as long as there are no breaking changes.
