### ISSUE TITLE
Add testing for test runs under sdist installs

### ISSUE THREAD

**Issue by sirosen** [nose-devs/nose2#377]
#375 raised this as an issue.

The current testing process only covers `git clone ...; tox`
When `nose2` is installed via a source distribution, it's possible for the contents of the package to differ from the repo. This can result in test failures.

An additional pair of builds should be added to the test matrix, one on python 2.7 and one on python 3.5 (or some other python3) which do something like the following:
```shell
python setup.py sdist
# there are a bunch of ways of getting the version number... this is an easy one
version="$(cat nose2/_version.py | \
    grep '^__version__' | \
    egrep -o '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+')"
(cd dist; tar -xzf nose2-${version}.tar.gz)
(cd dist/nose2-${version}; tox)
```

I don't think it's necessary to do this additional testing on every target interpreter version -- just one on py2 and one on py3 should be enough.

**Comment by katrinabrock** [comment]
Definitely agree this is a problem we need to solve in our CI.

Not convinced that best approach is to add additional builds vs packaging and installing from package for every build.
