### ISSUE TITLE
[Debian] Order of args in man page non-deterministic 

### ISSUE THREAD

**Issue by katrinabrock** [nose-devs/nose2#382]
From 
https://github.com/nose-devs/nose2/issues/381
>The order of the arguments seem to be non-deterministic as they rely on a set that is expressed in file nose2/session.py line 34. all_ being a set, the plugins order is inconsistent between multiple runs, and so the order of the usage from -h option is non-deterministic either. I recommend replacing all_ by a sorted(all_) in this line.

Haven't tried to reproduce this, just creating separate issue. Would accept a PR with the fix above, preferably  with a test that fails w/o the fix. 

cc: @P-EB

**Comment by P-EB** [comment]
Here's [what I did](https://github.com/nose-devs/nose2/files/1666325/doc.txt) into Debian.

**Comment by katrinabrock** [comment]
@P-EB Would merge this patch, please submit as a PR. 🙂

**Comment by P-EB** [comment]
Done
