### ISSUE TITLE
Test runs fail due to infintie recursion on Travis; unrelated to changes being tested

### ISSUE THREAD

**Issue by sirosen** [nose-devs/nose2#383]
Both #366 and #380 have been failing, but the failures are (1) not reproducible locally for me (2) appear related to test discovery in eggs, not the proposed changes.

So far, here's what I know:
- #366 and #380 are mild changes to the coverage plugin, but failures don't happen in tests of coverage at all
- Travis hits max recursion depth running in a loop on this line:
  https://github.com/nose-devs/nose2/blob/804b78b922bbe064efda4864eadf06e4da279f3a/nose2/plugins/loader/eggdiscovery.py#L62
- Debug logging from that function looks like this:
```
...
nose2.plugins.loader.eggdiscovery: DEBUG: find in egg dir /home/travis/build/nose-devs/nose2/nose2/tests/functional/support/scenario/tests_in_zipped_eggs/pkgegg-0.0.0-py2.7.egg pkgegg/ (pkgegg)
nose2.plugins.loader.eggdiscovery: DEBUG: find in egg dir /home/travis/build/nose-devs/nose2/nose2/tests/functional/support/scenario/tests_in_zipped_eggs/pkgegg-0.0.0-py2.7.egg pkgegg/ (pkgegg)
nose2.plugins.loader.eggdiscovery: DEBUG: find in egg dir /home/travis/build/nose-devs/nose2/nose2/tests/functional/support/scenario/tests_in_zipped_eggs/pkgegg-0.0.0-py2.7.egg pkgegg/ (pkgegg)
...
```
- Top of the call stack + test name looks like this:
```
======================================================================
ERROR: test_can_discover_test_modules_in_zipped_eggs (nose2.tests.functional.test_eggdiscovery_loader.EggDiscoveryFunctionalTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nose2/tests/functional/test_eggdiscovery_loader.py", line 38, in test_can_discover_test_modules_in_zipped_eggs
    self.assertTestRunOutputMatches(proc, stderr='FAILED \(failures=5, errors=1, skipped=1\)')
  File "nose2/tests/_common.py", line 82, in assertTestRunOutputMatches
    cmd_stdout, cmd_stderr = proc.communicate()
  File "nose2/tests/_common.py", line 227, in communicate
    **self.kwargs)
  File "nose2/main.py", line 306, in discover
    return main(*args, **kwargs)
  File "nose2/main.py", line 100, in __init__
    super(PluggableTestProgram, self).__init__(**kw)
  File "/opt/python/pypy2.7-5.8.0/lib-python/2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "nose2/main.py", line 133, in parseArgs
    self.createTests()
  File "nose2/main.py", line 258, in createTests
    self.testNames, self.module)
  File "nose2/loader.py", line 68, in loadTestsFromNames
    for name in event.names]
  File "nose2/loader.py", line 83, in loadTestsFromName
    result = self.session.hooks.loadTestsFromName(event)
  File "nose2/events.py", line 225, in __call__
    result = getattr(plugin, self.method)(event)
  File "nose2/plugins/loader/eggdiscovery.py", line 41, in loadTestsFromName
    return discovery.Discoverer.loadTestsFromName(self, event)
  File "nose2/plugins/loader/discovery.py", line 84, in loadTestsFromName
    self._find_tests_in_module(event, module, top_level_dir))
  File "nose2/plugins/loader/discovery.py", line 229, in _find_tests_in_module
    event, full_path, top_level_dir):
  File "nose2/plugins/loader/eggdiscovery.py", line 78, in _find_tests_in_dir
    event, modname, dist):
  File "nose2/plugins/loader/eggdiscovery.py", line 62, in _find_tests_in_egg_dir
    for test in self._find_tests_in_egg_dir(event, entry_path, dist):
```
- That test hasn't changed since 2014 (!)
- The top of the testcase has a somewhat suspect line...
  https://github.com/nose-devs/nose2/blob/804b78b922bbe064efda4864eadf06e4da279f3a/nose2/tests/functional/test_eggdiscovery_loader.py#L3

That's all I've got. I don't know why this shows up on these PRs and not on master, or why it would start failing now, or anything else really interesting.

**Comment by sirosen** [comment]
I can confirm that this happens even with a smaller and more benevolent change, as I have the result from a [branch which updated the installed version of setuptools](https://travis-ci.org/nose-devs/nose2/builds/336412876).

The only relevant thing I can find in the setuptools changelog (I was thinking that maybe one of the `pkg_resources` calls changed) is [this issue](https://github.com/pypa/setuptools/pull/1232), which touches on the right code.
Not being a setuptools expert, it's hard for me to tell whether or not this could have caused the issue, but I did try testing it out.

Using a version just before that change, `setuptools==38.2.3`, [passes on Travis](https://travis-ci.org/nose-devs/nose2/builds/336415980).
Using the version after that change, `setuptools==38.2.5`, [fails on Travis](https://travis-ci.org/nose-devs/nose2/builds/336418330).
AND, using the latest setuptools explicitly (and rebuilding my local `.tox/` dir), I can reproduce locally now.

IMO, that's pretty definitive.

I'm not sure whether or not this constitutes a setuptools bug -- I'll look at what we'd need to change to work with newer setuptools, to see if this maybe should be reported upstream as well.

**Comment by katrinabrock** [comment]
nice work in debugging this. :-D

I'll take a more detailed look at your changes within the next few days.

**Comment by duggelz** [comment]
Trying to debug this from the setuptools side.  How do I get the debugging output?  Is there a simple recipe to run a single test and see the output other than `make test`?  E.g. `test_can_discover_test_modules_in_zipped_eggs` is actually a number of tests that are run via recursively invoking nose2, how do I run one of those and look at the output, or ideally drop into the debugger?

**Comment by sirosen** [comment]
Hi @duggelz, thanks for looking into this.

That test case can easily be emulated as
```shell
$ PYTHONPATH=$PYTHONPATH:nose2/tests/functional/support/scenario/tests_in_zipped_eggs/pkgegg-0.0.0-py2.7.egg nose2 --log-level DEBUG -v --plugin=nose2.plugins.loader.eggdiscovery pkgegg
```
(from the repo root)

That includes debug output.

The way in which it runs is not 100% identical, but this does reproduce the buggy behavior on `master`.
