### ISSUE TITLE
[Debian] Maximum recursion depth exceeded on a test.

### ISSUE THREAD

**Issue by P-EB** [nose-devs/nose2#388]
Dear developers,

I met this bug in reproducible builds: https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/nose2.html

It doesn't seem to be fully deterministic. Does this ring any bell to you?

**Comment by katrinabrock** [comment]
I think this is #383 it's fixed in master.

**Comment by P-EB** [comment]
@katrinabrock do you have an idea about when you'll release a new version with this fix? :)

**Comment by sirosen** [comment]
I think this is an instance of #384 .
Leaving this open until that fix is released, but the underlying bug should have been resolved.

**Comment by katrinabrock** [comment]
yes, I want to merge #366 , #380, #387 then do a release this weekend.
