### ISSUE TITLE
Support for regex in test-method-prefix

### ISSUE THREAD

**Issue by Christina-Kang** [nose-devs/nose2#391]
Is there support for matching against a test method name (during test discovery) which is either match by suffix, or match on regex? I see only the option "test-method-prefix". If not, are there any future plans for this?

Thanks!

**Comment by sirosen** [comment]
The current implementation only supports fixed prefixes. (It's all done with `str.startswith` checks)

To my knowledge, nobody is working on or thinking about a suffix or regex matcher.
After looking at the parts of the source which handle this, I don't think it would be too hard to add, but I don't want to suggest changes without knowing why we're doing it.

What's your situation such that prefix matching doesn't work for you?

**Comment by sirosen** [comment]
Closing as a wontfix.

I'm not particularly opposed to this if there's really a need for it, but also don't want to add complexity without having a clear use-case.
Feel free to reopen if I'm way off-base.

**Comment by katrinabrock** [comment]
I'd accept a PR to make this configurable, but don't see a demonstrated need for it. Closing seems fine.
