### ISSUE TITLE
Plugins `junitxml` and `layers` don't seem to interact nicely.

### ISSUE THREAD

**Issue by neilvyas** [nose-devs/nose2#398]
I have a set of tests with both the given plugins enabled.

Starting yesterday, with no apparent updates of any code, I get the following error after every run of the whole test suite using `nose2 --config=setup.cfg ...`, whether the run was clean or not:

```
Internal Error: runTests aborted: 'LayerSuite' object has no attribute 'id'
```

I expected no error to be produced here, and the run to terminate successfully with an xml report.

I have tried disabling `junitxml` and the run seems to succeed until another part of my test flow fails because no xml report was produced. If this ticket gains any traction, I will attempt to run it without expecting an xml report and without junitxml to see if I can get a clean run.

I dug through the source for both plugins as well as `unittest.BaseTestSuite`, `unittest.TestSuite`, and `unittest.TestCase`, and my observations are:

1. I think this error is being raised by the `junitxml` plugin, because
    * it happens after all tests have been run, seemingly successfully;
    * there is no xml report produced; and
    * there is some suggestive code (detailed later).
2. I think this error is raised [right here](https://github.com/nose-devs/nose2/blob/master/nose2/plugins/junitxml.py#L120-L121), because
    * it's the only codepath I could find in the given packages that calls `test.id()`; and
    * it operates on all `event.test`s with no filtering, which means it might be operating on layer objects.
3. None of the `...Suite` classes define `id`, but `unittest.TestCase` does.

So, I think that we should guard the call to `id()` in `junitxml`'s source. It is somehow being called on a `LayerSuite` object instead of a `unittest.TestCase` object, which causes it to break, I think.

**Comment by katrinabrock** [comment]
Seems likely that there is some bug in combining these two plugins. 

The next step here would be to write a test that demonstrates this behavior. This would be a functional test. If you have time and inclination to do this, you can take a looked the existing scenarios: https://github.com/nose-devs/nose2/tree/master/nose2/tests/functional/support/scenario and use either an existing layers scenario or an existing junit scenario as a starting point for your testcase. 

Assuming your suspicions are correct (they seem logical), it seems odd that the `testOutcome` hook would be called on the `LayerSuite` in the first place. This seems undesirable in general, but if it is the case, changing it would be a pretty big breaking change considering users may have custom plugins that use this hook. Guarding the call to `id()` seems like a decent workaround to fix the immediate issue. At some point, we should write some tests with the layers plugin and a dummy plugin to check which hooks are getting called on the `LayerSuite` events and which are not.

**Comment by neilvyas** [comment]
Turns out that my issue was caused by an unrelated exception being thrown that was then swallowed by `junitxml`, which raised the "red herring" error of `Layersuite object has no attribute id`. Is this still a problem? Yeah. Is it pressing? probably not.

**Comment by katrinabrock** [comment]
@neilvyas feel free to raise an issue about the your exception getting swallowed and reopen this one. If you can provide an example case to make that happen, all the better.
