### ISSUE TITLE
Explicit testing of module rather than source path

### ISSUE THREAD

**Issue by CausticYarn** [nose-devs/nose2#400]
Is there any way to force nose2 to treat an argument as a module and try to import it?

The issue I'm having is in a continuous integration environment. I check out the code, install it, and want to run unit tests on the _installed_ module, not the checked out code (specifically to make sure everything needed is getting installed by setup.py).

If I run `nose2 package`, it treats the name package as the directory `package` checked out from source control, rather than a python module `package` that should be imported and have its tests run.  So tests pass because the files are present in source control that could fail once the module is installed.

I have a few workarounds but wondering if there is (or should be) a way to specify that the argument is a module/package?  Alternately can the START_DIR or TOP_LEVEL_DIRECTORY parameters be set to null or disabled to force nose2 to use the Python search paths instead?

**Comment by sirosen** [comment]
Are you sure that this is a matter of the package name being treated as a dirname?
I think it's quite likely that what's really happening is that you're being bitten by the fact that the current working dir is always the first element of [`sys.path`](https://docs.python.org/3/library/sys.html#sys.path). As a result, a local dir will be searched for packages before any other dirs, like `site-packages`.

If you change to a different directory and set the start dir, everything should work correctly.
If it doesn't, that would be quite interesting to me.
 For example, if your tests are in `tests/`, you could `cd tests/ && nose2 --start-dir ../`

Assuming that explanation is correct, changing this behavior isn't a simple matter of changing how `TOP_LEVEL_DIRECTORY` works -- that option adds more things to `sys.path`, but it doesn't remove anything.

If you really wanted, you could add a sitecustomize or pth file which removes the first entry of `sys.path`, but that seems like a dirty hack to me instinctively. Any of the more sophisticated ways in which I can imagine nose2 helping you do that are just polishing that same exact patch though -- not really changing what's going on.
