### ISSUE TITLE
3.3 CI broken 

### ISSUE THREAD

**Issue by katrinabrock** [nose-devs/nose2#403]
e.g. here https://github.com/nose-devs/nose2/pull/402
```
Collecting wheel
wheel requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 3.3.6
```

**Comment by katrinabrock** [comment]
Indeed, wheel has dropped support for python 3.3:
https://pypi.org/project/wheel/



> 0.30.0
> 
>     Added py-limited-api {cp32|cp33|cp34|…} flag to produce cpNN.abi3.{arch} tags on CPython 3.
>     Documented the license_file metadata key
>     Improved Python, abi tagging for wheel convert. Thanks Ales Erjavec.
>     Fixed > being prepended to lines starting with “From” in the long description
>     Added support for specifying a build number (as per PEP 427). Thanks Ian Cordasco.
>     Made the order of files in generated ZIP files deterministic. Thanks Matthias Bach.
>     Made the order of requirements in metadata deterministic. Thanks Chris Lamb.
>     Fixed wheel install clobbering existing files
>     Improved the error message when trying to verify an unsigned wheel file
>     Removed support for Python 2.6, 3.2 and 3.3.


I think we should as well. cc: @sirosen @artragis @ptthiem

**Comment by sirosen** [comment]
Yes, I don't think we need to explicitly state a policy that we don't test on or support EOL versions.
We should just drop them when we see issues. (Or, if someone wants to try to stay on top of this and proactively remove them as soon as they EOL, that's cool too.)
