### ISSUE TITLE
Nose execution unbuffered reporting 

### ISSUE THREAD

**Issue by nd842** [nose-devs/nose2#411]
It's possible to catch test information right after its execution (time, status, etc.) and not wait execution of all tests or suite?

**Comment by sirosen** [comment]
If you're writing a plugin, yes. [TestOutcomeEvents](https://nose2.readthedocs.io/en/latest/dev/event_reference.html#nose2.events.TestOutcomeEvent) trigger each time a test completes, and can be handled with [testOutcome](https://nose2.readthedocs.io/en/latest/dev/hook_reference.html#testOutcome) hooks.

Probably the simplest example of this in action is the [failfast plugin code](https://github.com/nose-devs/nose2/blob/master/nose2/plugins/failfast.py) which halts the testsuite when a failing test outcome is seen.
