### ISSUE TITLE
Should give the user more custom for testcase name like nosetest v1

### ISSUE THREAD

**Issue by gwind** [nose-devs/nose2#417]
https://github.com/nose-devs/nose2/blob/c6f56ed09cb8941367b2e39d64e23e1a78dd75ad/nose2/plugins/result.py#L236

if a testcase provide a custom testcase name by doc string or `shortDescription` method , we should not add the prefix like `str(test)`

```
    def _getDescription(self, test, errorList):
        if not isinstance(test, unittest.TestCase):
            return test.__class__.__name__
        doc_first_line = test.shortDescription()
        if self.descriptions and doc_first_line:
            desc = doc_first_line
        else:
            desc = str(test)
        event = events.DescribeTestEvent(
            test, description=desc, errorList=errorList)
        self.session.hooks.describeTest(event)
        return event.description
```

thanks,

**Comment by gwind** [comment]
more details in #417

**Comment by sirosen** [comment]
I'm not going to change this, at least not without some strong justification. If a PR were opened to add this as an optional behavior which users can opt-in to, I'd consider it.

The current test descriptions encode useful information. Many people are likely relying on the test description to help them find their way to tests which failed efficiently.

The utility of the test outcome reporting is always going to be a much higher priority than the prettiness of the test reports. For that reason, I'm closing this.

**Comment by gwind** [comment]
@sirosen Thanks for you reply.
I'm not familiar with unittest or nose2 now, I could ceate the PR when I have deep into the source code.
