### ISSUE TITLE
Can I custom the 'ok' for success testcase report?

### ISSUE THREAD

**Issue by gwind** [nose-devs/nose2#418]
https://github.com/nose-devs/nose2/blob/c6f56ed09cb8941367b2e39d64e23e1a78dd75ad/nose2/plugins/result.py#L149

I want to custom the 'ok' to `\033[92m\u2713\033[0m` for example, the testcase report would be like this:

![1540462911982](https://user-images.githubusercontent.com/98713/47493988-39fd0a00-d883-11e8-9489-b91a553d79c9.jpg)

This is more distinct for human.

Thanks

**Comment by gwind** [comment]
## Give my custom style

For unix-like system (macos and linux), run this to replace nose2 source:

```bash
#!/bin/bash

RESULT_PATH=$(python3 -c 'import os, nose2; print(os.path.join(os.path.dirname(nose2.__file__), "plugins/result.py"))')
# support sed in linux and macos
sed \
    -e '/self._report.*reportSuccess/s@ok@\\033[92m\\u2713\\033[0m@' \
    -e 's@desc = .*doc_first_line.*@desc = doc_first_line@' \
    ${RESULT_PATH} > /tmp/_result.py
mv /tmp/_result.py ${RESULT_PATH}
```

custom `shortDescription` method:

```python
class Bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

# ok '\033[92m\u2713\033[0m'
# \u21E8  ⇨
# \u21B3  ↳
# \u21E2  ⇢
# \u2B91  ⮑
# \u2937  ⤷
# \u27F3  ⟳
# \u2B51  ⭑
# \u2713  ✓


FIRST_ARROW = f"{Bcolors.OKGREEN}\u21E8{Bcolors.ENDC}"
SECOND_ARROW = f"{Bcolors.WARNING}\u21E2{Bcolors.ENDC}"


class BaseTestCase(tornado.testing.AsyncHTTPTestCase):

    main_title = None

    def shortDescription(self):
        class_doc = self.__doc__
        doc = self._testMethodDoc
        first = class_doc.split("\n")[0].strip() if class_doc else None
        second = doc.split("\n")[0].strip() if doc else None
        if not self.main_title:
            self.__class__.main_title = True
            return (f"\n{FIRST_ARROW} {Bcolors.BOLD}{first}{Bcolors.ENDC}\n"
                    f"  {SECOND_ARROW} {second}")
        return f"  {SECOND_ARROW} {second}"
```

**Comment by sirosen** [comment]
Specialization of the result format, especially at this level (with non-ascii chars and colors, stuff I'm _super_ wary of in a project that has to support Windows users too) is not an issue for the reporter itself to handle. It should simply delegate to some blob of user code.

This case should pretty easily be handled by implementing a custom plugin which handles `reportSuccess` events. The result reporter will respect already-handled events:
https://github.com/nose-devs/nose2/blob/c6f56ed09cb8941367b2e39d64e23e1a78dd75ad/nose2/plugins/result.py#L264-L266

**Comment by gwind** [comment]
@sirosen Thanks for you help, that would be nice if this can be complete with a custom hook.

https://nose2.readthedocs.io/en/latest/plugins/printhooks.html
