### ISSUE TITLE
[Proposal] Configuring Nose2 via env vars

### ISSUE THREAD

**Issue by rishavsharan** [nose-devs/nose2#419]
Hi guys

I work at MS Azure Devops which is a CI/CD system with a major focus on testing in pipelines. To give our users a rich reporting experience without forcing them to make any platform specific config, we want to be able to make changes to the reporting configs on the fly, in our pool machines.

This is something pytest allows via "PYTEST_ADDOPTS".
Essentially, something like `NOSE2_OPTS = --junit-xml DEFAULT` which would supercede the saved config in unittest.cfg

Currently, nose2 doesn't allows us to to do this. Adding this option will enable all the CI/CD platforms, and not just Azure DevOps, in providing a better test experience to nose2 users so that they will not have to do any platform specific configuration in their project code just to leverage the test reporting  capabilities of the platform.

Let me know what do you guys think. We would love to contribute to the nose2 community and submit PRs for this.

**Comment by sirosen** [comment]
I'd definitely be willing to look at a PR adding this feature.
If this doesn't see any action after a couple of months, I might circle back and take a crack at it myself -- it seems like a practical/useful addition without too much long term support burden for us.

**Comment by rishavsharan** [comment]
Thanks @sirosen great to hear your support for this! 
We would likely pick this up around the end of this year when we have the dev bandwidth.

**Comment by sirosen** [comment]
Realistically, I've had limited time for `nose2` and there's been no action on this at all. It's not, in retrospect, a terribly important feature. It could be added if someone had the drive to open a PR for it -- and I remain open to such a PR -- but since this is basically a drive-by feature request, I'm closing it to try to tidy up the repo.
