### ISSUE TITLE
Setup a mailing list, remove gitter badge, streamline communication

### ISSUE THREAD

**Issue by sirosen** [nose-devs/nose2#424]
This is a project management issue, not a code issue. This issue is partly a public way of showing how I plan to change nose2 communication.

A simple Google Group mailing list would be public, free, and require basically no maintenance. I like mailman better when someone else is on the hook for keeping it running, but Google Groups work well enough. The Jenkins dev community relies on Google Groups.

As part of #423, I'd like to maybe ditch the gitter badge and just link to the mailing list instead.

IM may be more appropriate for immediate communication, but email is much more appropriate to the pace of this project and integrates more directly with people's existing workflows. Signing up for digest mail is easy.

**Comment by ptthiem** [comment]
Sounds good.

**Comment by sirosen** [comment]
I've had a long and unintentional hiatus from nose2 work, but I'm trying to get this done and plan to publish v0.9.0 shortly as well.

To fill in some more detail:
- I've registered `nose2.io` as a domain (registration is in a pending state as I write this)
- I want to setup redirection for `nose2.io -> docs.nose2.io` and `docs.nose2.io` as the default for readthedocs
  - readthedocs needs to have a CNAME, so it _has_ to be a subdomain, hence the extra redirect
- If I can get that all sorted out, I'll release 0.9.0 once the new docs site is live and I've checked that redirects are all clean/working

- I will setup nose2 mailing as a GSuite domain and setup discuss@nose2.io as a public group / mailing list
- Final step will be to drop the Gitter badge and move discussion to the mailing list by noting it in the readme
