### ISSUE TITLE
Apply black, isort, flake8, and flake8-bugbear as coding standards

### ISSUE THREAD

**Issue by sirosen** [nose-devs/nose2#440]
I'm using these at work and, personally, love the results. It took a while to "surrender" to the autoformatters, but once you completely cede control over formatting, the results are fast, reliable, and free up your brain for better things.

I would like to let this sit open for comments for a few weeks (months?) before taking action.
Barring any objections, I'll do this and setup appropriate tooling + additions to the contrib doc.

In my experience, slow and systematic rollout of these tools to an older code-base is _not_ the easiest way. Rather, make one very large, very loud "bang!" and then have it be over with.

**Comment by honnix** [comment]
Go for it. There are only two open PRs currently. Do a big bang and help those authors rebase shouldn't be much work.

**Comment by sirosen** [comment]
Fun fact for anyone looking at this issue: it sat in my backlog for a long time because nose2 actually has tests that get broken by `black`. I didn't expect this at first, but because we have tests which print chunks of "user code", autoformatting the testsuite results in test failures.
I'm taking another look at this after a long hiatus, and should be able to plug the holes with `fmt: off` comments. I have my fingers crossed that I can get this done this weekend.

**Comment by sirosen** [comment]
This was done. Doing a quick check here for any new issues and I noticed this was still open.
