### ISSUE TITLE
Support configuring through pyproject.toml

### ISSUE THREAD

**Issue by flying-sheep** [nose-devs/nose2#452]
The [`tool` table section](https://www.python.org/dev/peps/pep-0518/#tool-table) of PEP 518 says that tools should store their name in `[tool.<pypiname>]` in `pyproject.toml`.

**Comment by sirosen** [comment]
I need to look at the TOML spec again, but I think it should be pretty reasonably possible to put the contents of `nose2.cfg` into `[tool.nose2]` in `pyproject.toml`
We'll have to pull in a TOML parser for this, but it looks like `toml` supports old pythons, so it won't be much of an issue.

I'd be happy to review a PR adding support. (I'm unlikely to work on this myself unless there's an indication of general demand.)

**Comment by flying-sheep** [comment]
It’s more of a “it’s the correct way to do it” thing. I’m not using nose2, I’m just maintaining a list of projects that have support already.

**Comment by sirosen** [comment]
Gotcha. In that case, thanks for being a good citizen and flagging this for me. 👍 

Since nose2 is a "maintenance first" project at this stage in its life, I just try to set clear expectations on these things.

**Comment by laike9m** [comment]
Definitely want to see this happen.

**Comment by sirosen** [comment]
Via #596, #606 I now have this merged into `main`.

I'll be releasing this week, at which point I'll close this issue and anyone interested should hopefully see a ping that `pyproject.toml` support is available.

**Comment by sirosen** [comment]
v0.15.0 is now available, with support for reading config from `tool.nose2` in `pyproject.toml`. :tada: 

Please open issues if you see any problems with the new version!
