### ISSUE TITLE
Add support for pre-commit hooks

### ISSUE THREAD

**Issue by willianpaixao** [nose-devs/nose2#459]
currently I'm using nosetests as a "system hook" [this way](https://github.com/pre-commit/pre-commit-hooks/issues/115).

But nose is also a Python application and it's pretty straight forward to register it as an [official hook](https://pre-commit.com/hooks.html), by basically adding an `.pre-commit-config.yaml` to the root of the repo.

**Comment by sirosen** [comment]
I'm generally a fan of pre-commit and use it on any new projects these days, but if you wanted to run your testsuite as a pre-commit hook, I'd generally suggest you do that by making it a local hook (which it sounds like you're doing).

I'm not really against this, but it is not as trivial to create a hook as it is to use one, and I don't really see the value.

I'd encourage you, if you want to see this through, to create a hook repo and get it added to pre-commit's list. This doesn't need to be in nose2 at all.
