### ISSUE TITLE
Enabling [doctest] always-on = true makes nose2 exit with "error: no commands supplied"

### ISSUE THREAD

**Issue by mgedmin** [nose-devs/nose2#460]
I'm trying to migrate check-manifest's test suite from nose to nose2.  I have a couple of doctests I'm trying to include in the test suite, by creating a `unittest2.cfg` with

```ini
[unittest]
plugins = nose2.plugins.doctests

[doctest]
always-on = true
```

However as soon as I do that, running `nose2` with no command-line arguments fails:

```
$ nose2
usage: nose2 [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: nose2 --help [cmd1 cmd2 ...]
   or: nose2 --help-commands
   or: nose2 cmd --help

error: no commands supplied
```

I can comment out the `always-on = true` line and then nose2 runs all the tests (but no doctests).

**Comment by stefanholek** [comment]
Hi Marius!

I ran into this the other day. The problem is that on its quest to find doctests nose2 imports the project's setup.py, which is of course impossible.
