### ISSUE TITLE
Configuration documentation doesn't say what file name you need

### ISSUE THREAD

**Issue by boxed** [nose-devs/nose2#467]
https://docs.nose2.io/en/latest/configuration.html#configuration-files is missing a bit of crucial information: what is the name of the .ini file? It looks like it can be both "unittest.cfg" or "nose2.cfg" if I read the code. Is this correct?

**Comment by sirosen** [comment]
Yes, it's `unittest.cfg` or `nose2.cfg` by default. The docs say so, [but only under the `-c` option](https://docs.nose2.io/en/latest/configuration.html#cmdoption-c), not where the use of ini config is first mentioned.

I think the doc could actually expand out into separate paragraphs to put this towards the top, something like
> nose2 can be configured via standard, ini-style config files. The default files are `unittest.cfg` and `nose2.cfg` in the start directory.
>
> [more doc in following paragraph]

I'll close this when I can make a tweak to the doc to make this more prominent.
