### ISSUE TITLE
How to test a function with keyword args?

### ISSUE THREAD

**Issue by szalpal** [nose-devs/nose2#479]
Hello!

### Question
How could I test a function, that accepts keyword args, parameterizing it by a subset of those args? I've tried an approach with test generator, but I'd appreciate any other idea/suggestion 

### Problem
Let's say, I have such function:
```python
def func_under_test(arg1=None, arg2='string', arg3=[1, 2, 3]):
    # do something
```
Now, while testing, I'd like to leave some of the arguments with their default values. Something like:
```python
def check_func(**kwargs):
    ret = func_under_test(**kwargs)
    # assert ret

def test_func():
    args = [
        {'arg1': 42, 'arg3': [1, 2, 3]},
        {'arg1': 24, 'arg3': [4, 5, 6]},
    ]
    for a in args:
        yield check_func, **a  # This won't work
```
Obviously, the code above won't work. I guess it's because nosetest generator needs to yield a tuple. Since the arguments to the function under test can vary much, I'm not able to explicitly unpack the `args` dict to a tuple (like `yield check_func, args['arg1'], args['arg2'] etc...`).The "working" equivalent of what I'd like to achieve is an explicit loop:
```python
def test_func():
    args = [
        {'arg1': 42, 'arg3': [1, 2, 3]},
        {'arg1': 24, 'arg3': [4, 5, 6]},
    ]
    for a in args:
        check_func(**a)
```
but this will hide the test cases into one big "umbrella" case, which ofc I'd like to evade.

### What I tried
I tried using `namedtuple`, but this doesn't seem to be working:
```python
from collections import namedtuple

def test_func():
    args = [
        {'arg1': 42, 'arg3': [1, 2, 3]},
        {'arg1': 24, 'arg3': [4, 5, 6]},
    ]
    nt = namedtuple('func_tpl', 'cf arg1 arg3')
    for a in args:
        check_tpl = nt(check_func, a['arg1'], a['arg3'])
        yield check_tpl
```

**Comment by sirosen** [comment]
There are at least two basic approaches for producing a test-case per set of parameters which handle keyword args gracefully.

1. Wrap the function under test

Use a wrapper to consume args and/or kwargs and pass them to the function you want to test.
e.g.
```python
def check_wrapper(kwargs):
    ret = my_func(**kwargs)
    assert ret  # e.g. the function should return a truthy value

def test_my_func():
    for params in [{}, {"foo": 1}, {"foo": False, "bar": "baz"}]:
        yield check_wrapper, params
```

You could get more sophisticated and do things like pass parameters and expected return values in this way.

2. Use `nose2.params` to pass parameters directly to a test function

```python
from nose2.tools import params

@params({}, {"foo": 1}, {"foo": False, "bar": "baz"})
def test_my_func(kwargs):
    ret = my_func(**kwargs)
    assert ret  # e.g. the function should return a truthy value
```

---

Personally, I think the test generator syntax is much less readable than a parameterized test, so I would almost always opt for the latter.
