### ISSUE TITLE
nose2 tests fails with "AttributeError: __abstractmethods__"

### ISSUE THREAD

**Issue by xqt** [nose-devs/nose2#480]
running a test with

  nose2 tests.l10n_tests

fails with AttributeError: __abstractmethods__ .
You will find the full traceback here: https://phabricator.wikimedia.org/T244087

**Comment by sirosen** [comment]
There's insufficient information here for me to try to reproduce and resolve this issue.
It seems like you have an abstract test class, or something of that nature. Maybe it was supported by `nose`, but `nose2` doesn't support all of the test configurations and usages from `nose`. So it's not even definitive at this point that there's any bug in `nose2`.

I see, in the issue you linked, mention of `nose3`. As one of the current `nose2` maintainers, I have no idea what that project is and am not able to find clarity with some quick searching. It looks, at a glance, like a re-upload of the (at this point, long dead) `nose` code, but I don't know why someone would do that.

If you can provide example code that reproduces this issue, ideally something minimal, I'm happy to look into it.

**Comment by xqt** [comment]
We use pytest with pytest-attrib now instead instead of nose
