### ISSUE TITLE
Please add links from old "nose" to "nose2"

### ISSUE THREAD

**Issue by jedie** [nose-devs/nose2#540]
I find "nose2" just by accident.

Please add **fat** links from old `nose` package to `nose2`.

e.g. here:

![grafik](https://user-images.githubusercontent.com/71315/187285506-aa4ea9b3-f1bf-4d4b-a433-ad3e42b422fc.png)

**Comment by sirosen** [comment]
Unfortunately, I'm not sure this is feasible. All or almost all of the nose developers have moved on to other projects, and some have changed/updated the accounts which they use and aren't easily reachable.

I'm not going to close summarily, but there's little that I can do on this front. I'll leave it open for a while in case someone has an idea about how to clarify things in the `nose` project readme, but if there's no meaningful activity after a few weeks, I'll probably circle back and close this.
