### ISSUE TITLE
sdist: PKG-INFO should list license.txt in License-File

### ISSUE THREAD

**Issue by mtelka** [nose-devs/nose2#551]
The sdist at PyPI contains this:
```
$ grep -i license nose2-0.12.0/PKG-INFO
Classifier: License :: OSI Approved :: BSD License
License-File: AUTHORS
$
```
But the actual `nose2` license is in `license.txt` file.  Please add `license.txt` to `PKG-INFO`.

Thank you.

**Comment by sirosen** [comment]
It took a long time for me to circle back on this, but I've finally gotten a chance to work on `nose2` a bit and should have this fixed shortly. It's a bit of an oddity how this happened -- see #573 for details. I've got a few more minor tweaks and then there will be a release with this included.
