### ISSUE TITLE
Test fails due missing mod.py

### ISSUE THREAD

**Issue by mtelka** [nose-devs/nose2#552]
I tested with the sdist from PyPI and tox failed with this error:
```
py39 run-test: commands[2] | coverage report
No source for code: '/tmp/tmpvb1ie5o6/mod.py'.
Aborting report output, consider using -i.
ERROR: InvocationError for command /usr/bin/coverage report (exited with code 1)
```
To test I run this: `tox --current-env --no-provision --recreate -e py39`.

**Comment by sirosen** [comment]
Sorry it took so long to get a response on this!

I just did the 0.13.0 release and tested on that sdist, to see if I could reproduce this issue, but I was not able to do so.

If there was a packaging bug, it may have been solved. I'll leave this open for a bit in case you are still seeing this, but I intend to close in a while as a CNR.

**Comment by mtelka** [comment]
I think this was a bug in coverage.
