### ISSUE TITLE
License terms for unittest2?

### ISSUE THREAD

**Issue by musicinmybrain** [nose-devs/nose2#553]
The license file indicates that some of the code is derived from unittest2:

https://github.com/nose-devs/nose2/blob/5375b1d5eee5fa59a1785098fedc4441d6cfcb55/license.txt#L30-L32

The link http://docs.python.org/license.html does not make it clear what license terms are intended here, and I’m not sure that this is the right link anyway since unittest2 was never part of the standard library.

The [pypi package for `unittest2`](https://pypi.org/project/unittest2/) has a “BSD” license trove classifier, and its `setup.py` references http://www.voidspace.org.uk/python/license.shtml, a now-dead link that [previously hosted “The Voidspace Open Source License” (Wayback Machine)](http://web.archive.org/web/20200709010030/http://www.voidspace.org.uk/python/license.shtml), which was a [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html) license. I think that license text is what should apply here.

If you believe these are the correct terms for unittest2 code in nose2, would you consider updating the license file with the actual license text?

**Comment by sirosen** [comment]
Thanks so much for your research on this!

> I’m not sure that this is the right link anyway since unittest2 was never part of the standard library.

I agree. I'll pull in the unittest2 license material as soon as I'm able.

---

There's another issue which opened today about the license file being missing from the sdist, so I think I have some general metadata tweaking to do. Hopefully I can make time today or this weekend to take care of it.

**Comment by sirosen** [comment]
I've finally gotten things settled enough in terms of my other work, projects, etc that I can make time for this _plus_ having refocused and realized that I've left some `nose2` work hanging. I'm sorting out the issue right now, and I'll have a release shortly to resolve this (among other things).

> Hopefully I can make time today or this weekend to take care of it.

:sweat_smile:
