### ISSUE TITLE
tests in the published code

### ISSUE THREAD

**Issue by JCHacking** [nose-devs/nose2#602]
If we try `pip install nose2` and look at the contents of the folder, we can see that there is the directory with the tests.
```
» ls -l  venv/lib/python3.11/site-packages/nose2         
total 144
-rw-r--r-- 1 jchacking jchacking  2892 abr 14 11:46 collector.py
-rw-r--r-- 1 jchacking jchacking  2267 abr 14 11:46 config.py
-rw-r--r-- 1 jchacking jchacking 36448 abr 14 11:46 events.py
-rw-r--r-- 1 jchacking jchacking   433 abr 14 11:46 exceptions.py
-rw-r--r-- 1 jchacking jchacking   109 abr 14 11:46 __init__.py
-rw-r--r-- 1 jchacking jchacking  4227 abr 14 11:46 loader.py
-rw-r--r-- 1 jchacking jchacking   197 abr 14 11:46 __main__.py
-rw-r--r-- 1 jchacking jchacking 11780 abr 14 11:46 main.py
drwxr-xr-x 4 jchacking jchacking  4096 abr 14 11:46 plugins
drwxr-xr-x 2 jchacking jchacking  4096 abr 14 11:46 __pycache__
-rw-r--r-- 1 jchacking jchacking  4609 abr 14 11:46 result.py
-rw-r--r-- 1 jchacking jchacking  2091 abr 14 11:46 runner.py
-rw-r--r-- 1 jchacking jchacking  8186 abr 14 11:46 session.py
-rw-r--r-- 1 jchacking jchacking  8746 abr 14 11:46 sphinxext.py
-rw-r--r-- 1 jchacking jchacking  5128 abr 14 11:46 suite.py
drwxr-xr-x 5 jchacking jchacking  4096 abr 14 11:46 tests
drwxr-xr-x 3 jchacking jchacking  4096 abr 14 11:46 tools
-rw-r--r-- 1 jchacking jchacking 11245 abr 14 11:46 util.py
``` 

It is not useful for the client to have these files, so my proposal is to move the tests folder out of nose2.

**Comment by JCHacking** [comment]
I am working on it, when I have it I will publish a PR.

**Comment by sirosen** [comment]
The tests are intentionally included in the built distribution because they are valuable to nose2 redistributors (e.g. Linux distros). There's even explicit CI testing to ensure that those copies of the tests work. 

Are they posing a particular problem for you? I'm not totally averse to removing them but we'd have to reach out to the distro maintainers to ensure they all switch to repo source builds (which is a growing trend, since packages don't always include their test requirements).

**Comment by JCHacking** [comment]
It does not generate any problems, but it is unnecessary code for the client.

**Comment by JCHacking** [comment]
So you are right, to avoid breaking other library packages, and because it doesn't really cause problems we leave the tests inside nose2.
Thanks for listening!
