### ISSUE TITLE
The tag for 0.14.2 is missing

### ISSUE THREAD

**Issue by dvzrv** [nose-devs/nose2#607]
Hi! :wave: 

I'm packaging this project for Arch Linux and noticed that there is no tag for 0.14.2 in this repository.
Can you please add it? It blocks me from upgrading.

**Comment by sirosen** [comment]
Oh, sorry about that! I think I have it tagged locally but didn't push. I'll fix that after my morning commute, first thing when I get to a desk. (A couple of hours from now.)

**Comment by sirosen** [comment]
I just pushed the tag up; let me know if there's any issue pulling/building/using it.
Thanks for catching this and filing the issue!
