### ISSUE TITLE
v0.15.0 seemed to break my ini config

### ISSUE THREAD

**Issue by grhwalls** [nose-devs/nose2#614]
Here is my ini config file:
```
[flake8]
max-line-length = 120
extend-ignore = E722

[unittest]
plugins = nose2.plugins.layers
          nose2.plugins.junitxml

[junit-xml]
always-on = False
keep_restricted = False
path = nosetests.xml
test_fullname = False

[layer-reporter]
always-on = True
colors = False
```

Running `nose2 -c tox.ini --junit-xml <testNames>` I get:
`nose2: error: Unrecognized arguments: --junit-xml`

Reverting back to v0.14.2 fixes my issue.

**Comment by sirosen** [comment]
Do you have a `pyproject.toml` for your repo? 0.15.0 introduces the possibility of config in `[tool.nose2]` there, so there are two easy possibilities:
- the loading code is somehow broken and is overwriting your config
- you have a `[tool.nose2]` table (which used to do nothing) and which now messes things up

I wouldn't be shocked if the TOML loading code is imperfect. It's the first time that codepath has been touched in a really long time. But I need a little more info to reproduce this.

**Comment by grhwalls** [comment]
pyproject.toml:
```
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "axi_hw_devices"
description="Library for device specific operations"
readme = "README.rst"
requires-python = ">=3"

# these are direct, imported dependencies. There may be other packages which are assumed, but
# since alternate packages are possible to use (as long as they have similar interfaces), they are
# not called out explicitly here.
dependencies = [
]

dynamic = ["version"]

[project.optional-dependencies]
dev = [
  "build",
  "nose2",
  "flake8",
  "twine",
]
test = [
  "axi_hw_devices[dev]",
  "vivado_jtag >= 3.0.0.dev",
  "xil_axi_ip >= 2.1.0.dev",
]

[tool.setuptools]
packages = ["axi_hw_devices",]

[tool.setuptools.dynamic]
version = {attr = "axi_hw_devices.version.__version__"}
```

**Comment by sirosen** [comment]
I just looked into this and figured it out. It seems obvious in hindsight, but there's a bug introduced in the new pyproject.toml loading code in which it won't read config files (even those passed with `-c`) if they don't end in `.cfg`.

It's simply an incorrect conditional being used to dispatch between INI loading and pyproject.toml loading.

I'm cooking up a regression test, and then I'll make the fix. Expect a v0.15.1 to ship within the next few hours ( :crossed_fingers: ).

**Comment by sirosen** [comment]
v0.15.1 is now available! :tada: 

Please let me know if it clears things up (as it should) or if you see other issues.

**Comment by grhwalls** [comment]
v0.15.1 fixed my issue! Thanks!
