### ISSUE TITLE
Add hooks for before and after code import

### ISSUE THREAD

**Issue by leth** [nose-devs/nose2#81]
It's currently not possible to collect coverage for code which is executed on module import without also collecting coverage of the nose2 codebase.

If there were hooks for before and after code import they could be used to start/stop coverage collection, limiting it only to project code.

**Comment by leth** [comment]
I'm looking into this again, and would like some advice on what would be preferable.

I can could add the following hooks. Which would be preferable, or is there a better option?
- before & after hook for each import call
- after hook for each load loadTestsFrom*

Are there any diagrams showing the lifecycle of hooks and events happen during a nose2 run?

**Comment by thedrow** [comment]
I don't think that there are any diagrams showing the lifecycle of hooks and events.
I think that the second option could be useful to other people as well.
Could this hook affect the selection of which tests to run?

**Comment by leth** [comment]
Sounds like a good idea; do you know of any events which do something similar so I can see how it's done?

**Comment by leth** [comment]
Fixed by #244
